// Known raid loot items — used by the "Raid loot only" filter.
// Names are stored lowercase so comparisons are case-insensitive.
window.RaidLootItems = new Set([
  "axe of the kromzek kings",
  "boots of the storm",
  "crown of the kromzek kings",
  "ring of lightning",
  "the horn of hsagra",
  "velium encrusted gauntlets",
  "white dragon scale sash",
  "wrist guard of thunder",
  "boots of the vindicator",
  "chestplate of vindication",
  "living thunder earring",
  "white bear pelt cloak",
  "breastplate of eradication",
  "cloak of the falling stars",
  "hammer of battle",
  "iron scroll of war",
  "reaver",
  "swiftblade of zek",
  "blade of carnage",
  "flayed barbarian hide mask",
  "flayed barbarian skin leggings",
  "helmet of rallos zek",
  "ring of destruction",
  "war bow of rallos zek",
  "clawed griffin sword",
  "white dragon helm",
  "white dragonscale boots",
  "tri-plated golden hackle hammer",
  "cowl of mortality",
  "cracked claw of zlandicar",
  "first brood talisman",
  "frakadar's talisman",
  "gauntlets of mortality",
  "massive dragonclaw shard",
  "zlandicar's heart",
  "zlandicar's talisman",
  "aegis of ice",
  "frostreaver",
  "frostreaver's embroidered cloak",
  "frostreaver's velium crown",
  "ring of winter",
  "dain frostreaver's head",
  "king tormax's head",
  "yelinak's head",
  "bestial tunic",
  "blade of the swarm",
  "braid of golden hair",
  "chestplate of stability",
  "essence of nature",
  "fist of nature",
  "girdle of living thorns",
  "golden leaf earring",
  "massive heartwood thorn",
  "melodic breastplate",
  "nature's melody",
  "noctivagant breastplate",
  "petrified heartwood flamberge",
  "resplendent robe",
  "robe of the bonecaster",
  "sap encrusted branch",
  "silver moon chest wraps",
  "sorcerer's robe",
  "spirit weaver's breastplate",
  "ayill's aged stone shield",
  "circlet of the struggle",
  "craslith",
  "dragon's eye sage ring",
  "dragons blood earring",
  "dragons tear earring",
  "mask of the dragon slayer",
  "outrider's taming whip",
  "sacrifice",
  "soul defiler",
  "very large coin purse",
  "yelinak's talisman",
  "ancient prismatic axe",
  "ancient prismatic battlehammer",
  "ancient prismatic bow",
  "ancient prismatic brawl stick",
  "ancient prismatic claymore",
  "ancient prismatic fist wraps",
  "ancient prismatic lance",
  "ancient prismatic mace",
  "ancient prismatic spear",
  "ancient prismatic staff",
  "ancient prismatic stiletto",
  "ancient prismatic warsword",
  "fist of pummeling prowess",
  "velium fraught shackles",
  "primal velium reinforced bow",
  "sightless velium eye",
  "priceless velium claidhmore",
  "primal velium battle axe",
  "primal velium battlehammer",
  "primal velium brawl stick",
  "primal velium claidhmore",
  "primal velium spear",
  "primal velium warsword",
  "tome of innovation",
  "besmirched mask of conception",
  "boots of the ancients",
  "bracchium secundae",
  "clandestine veil of m`rata",
  "clawed coat of tyro",
  "despondent shroud",
  "dowel of the secundarum",
  "eye of tjudawos",
  "fascia secundae",
  "fedora secundae",
  "gloves of temperantia",
  "heritage of secundae",
  "legacy of tyro",
  "lungi of the forbidden",
  "premier bow of secundae",
  "sharpened dragon's scale",
  "surreptitious brooch",
  "tenuous dragonscale slippers",
  "tyro's manuscript",
  "clawed guardian bracer",
  "white resistance stone",
  "dragon scaled mask",
  "red resistance stone",
  "blue resistance stone",
  "dainty gloves",
  "mask of tinkering",
  "green resistance stone",
  "shroud of longevity",
  "barrier of sound",
  "bow of the silver fang",
  "melodic charm",
  "ring of superiority",
  "runed fang necklace",
  "shadow fang necklace",
  "shield of fury",
  "shield of thorns",
  "shield of the protector",
  "shield of the wurms",
  "amulet of the dreadgazer",
  "circlet of summer",
  "hand of the master",
  "mask of fall",
  "reaper's ring",
  "rocksmasher",
  "whitestone shield",
  "blackstar, mace of night",
  "cekenar's claw",
  "frosted ice spike",
  "meljeldin, bane of giants",
  "silver dagger of destruction",
  "wurmscale fistwraps",
  "ancient wurm hide greaves",
  "ancient wurm hide robe",
  "belt of the destroyer",
  "boots of the destroyer",
  "bow of the destroyer",
  "dagarn's tail",
  "shining metallic pantaloons",
  "wurm claw pauldrons",
  "bracelet of the sky",
  "claw of lightning",
  "cloak of the sky",
  "fist of lightning",
  "mask of the sky",
  "onyx chain sleeves",
  "ring of the sky",
  "twisted steel bastard sword",
  "twisted steel gauntlets",
  "bracelet of protection",
  "eye of the rigtorgn",
  "rekeklo's war sword",
  "shovel of the harvest",
  "ancient wyvern hide boots",
  "ancient wyvern hide leggings",
  "ancient wyvern hide sleeves",
  "ancient wyvern hide tunic",
  "cloak of venom",
  "ikatiar's stinger",
  "mask of venom",
  "poison soaked tunic",
  "blydreln's bane",
  "crown of resiliance",
  "earring of the icecaster",
  "facesmasher",
  "helmet of the crawler",
  "onyx chain leggings",
  "silver chains",
  "sprinkler of the spirits",
  "ebony headband",
  "frostwrath",
  "mithril boots",
  "mithril gauntlets",
  "mithril helm",
  "orb of the crimson bull",
  "shawl of perception",
  "cloak of thorns",
  "girdle of dark power",
  "mask of terror",
  "medal of deep thought",
  "nevederia's claw",
  "nevederia's horn",
  "nevederia's left eye",
  "nevederia's right eye",
  "boots of superiority",
  "breastplate of superiority",
  "gloves of stability",
  "silver girdle of stability",
  "truesight helmet",
  "amulet of the storm",
  "beldron's vambraces of impiety",
  "boots of the dead dream",
  "chestplate of fiery might",
  "sky watcher's monocle",
  "staff of the silent star",
  "thunderstone",
  "vambraces of discontent",
  "ancient pirate's eyepatch",
  "bracelet of the deep sea",
  "greaves of the deep sea",
  "helm of the deep sea",
  "net of the deep sea",
  "orb of the deep sea",
  "siren song, dagger of the sea",
  "trident of the deep sea",
  "ancient fire etched flamberge",
  "dawncaller, blade of the morning",
  "flame etched short sword",
  "kreizenn's flame",
  "shiny metallic gloves",
  "shiny metallic sleeves",
  "silver disk",
  "verlekarnorm's horn of disaster",
  "dragonrib club",
  "gaudralek, sword of the sky",
  "onyx gauntlets",
  "silver bracelet of rage",
  "silver whip of rage",
  "sledge of smashing",
  "vyemm's fang",
  "vyemm's left eye",
  "vyemm's right eye",
  "axe of resistance",
  "great spear of dawn",
  "shield of midnight",
  "shield of the dawn",
  "black rock maul of crushing",
  "circlet of suffering",
  "emerald bastardsword of purity",
  "lance of thunder",
  "necklace of nightstalking",
  "pauldrons of blight",
  "transparent eyepatch",
  "true mithril breastplate",
  "baton of flame",
  "dragon skin bracelet",
  "dragonspine rapier",
  "spinning orb of confusion",
  "tvenken's slippers of silence",
  "windraider's belt",
  "abashi's rod of disempowerment",
  "akkirus' mask of warfare",
  "brother xave's headband",
  "camii's bracer of vigor",
  "crystasia's crystal ring",
  "do`vassir's gauntlets of might",
  "feeliux's cord of velocity",
  "gharn's rock of smashing",
  "hobart's war helmet",
  "jaelen's katana",
  "kelsiferous' armband of artistry",
  "maclaer's boots of silence",
  "mrylokar's dagger of vengeance",
  "palladius' axe of slaughter",
  "rowyl's metal armguards",
  "sal`varae's robe of darkness",
  "sirran's boots of insanity",
  "solist's earring of insight",
  "ssra's bloodstone eyepatch",
  "tolan's longsword of the glade",
  "valtron's necklace of wonder",
  "viik's pauldrons of pain",
  "vyrinn's earring of insanity",
  "yakatizma's shield of crafting",
  "doljonijiarnimorinar",
  "efreeti ice staff",
  "frost-covered tome",
  "frozen efreeti boots",
  "frozen turban",
  "glowing red stone",
  "icicle tunic",
  "icicle wristband",
  "ring of the frozen flame",
  "bone bracelet of condemnation",
  "bone ring of condemnation",
  "boots of bladecalling",
  "bracelet of frostbite",
  "crystal crown of confusion",
  "crystal rod of confusion",
  "gloves of bladecalling",
  "shield of the freezing winds",
  "silver sword of yalrek",
  "snow storm mask",
  "velketor's spell book",
  "vermilion orb of torrefaction",
  "vermilion robe of torrefaction",
  "worn great staff",
  "crescent blades of luclin",
  "scimitar of the emerald dawn",
  "skydarkener",
  "tanglewood shield",
  "blood orchid katana",
  "katana of endurance",
  "maelstrom",
  "shissar deathspeaker staff",
  "shissar focus staff",
  "skullcrusher of kragg",
  "fatesealer",
  "shissar apothic staff",
  "sword of the shissar",
  "atrebe's diabolic sprinkler",
  "blackstone maul",
  "bo staff of trorsmang",
  "pulsating gem",
  "sprinkler of suffering",
  "robe of the azure sky",
  "shield of elders",
  "shroud of veeshan",
  "yunnb's earring",
  "malevolent runeblade",
  "razor fang of xygoz",
  "staff of null",
  "blood ember breastplate",
  "cloak of piety",
  "cobalt breastplate",
  "deepwater breastplate",
  "donal's chestplate of mourning",
  "elder spiritist's breastplate",
  "jaundiced bone breastplate",
  "mana robe",
  "mrylokar's breastplate",
  "poisoned mantle",
  "siblisian berserker cloak",
  "singing steel breastplate",
  "tolan's darkwood breastplate",
  "tunic of wrath",
  "undead dragon sinew",
  "wild lord's tunic",
  "ancient shissar gauntlet",
  "blood ember greaves",
  "cobalt greaves",
  "deepwater greaves",
  "diamond encrusted staff",
  "donal's leggings of mourning",
  "elder spiritist's greaves",
  "gnarled staff",
  "jaundiced bone greaves",
  "leggings of wrath",
  "lycanthropic staff",
  "mrylokar's greaves",
  "nightshade scented staff",
  "shissar guardian staff",
  "shissar nullifier staff",
  "singing steel greaves",
  "tolan's darkwood greaves",
  "waters of impenetrable aura",
  "wild lord's trousers",
  "tobrin's mystical eyepatch",
  "grey suede boots",
  "blade of falling stars",
  "left eye of xygoz",
  "veldrak's shortblade",
  "shissar protection staff",
  "sarnak summoners staff",
  "veridix's shortsword",
  "howling cutlass",
  "nightfall",
  "robe of adversity",
  "ykeshan broad axe",
  "claw of phara dar",
  "crown of rile",
  "sword of rile",
  "frozen zweihander",
  "razor sharp short sword",
  "smoldering cudgel",
  "spear of constriction",
  "robe of conjuration",
  "sceptre of destruction",
  "writ of dragonkind",
  "smolder",
  "staff of the elder claws",
  "salindrite dagger",
  "shield of the clawed guardian",
  "staff of the morning dew",
  "eye of kildrukaun",
  "eye of vyskudra",
  "eye of zeixshi-kar",
  "katana of pain",
  "circlet of silver skies",
  "cloak of silver eyes",
  "unopenable box",
  "wand of the black dragon eye",
  "lendiniara's talisman",
  "mask of superiority",
  "ring of relkententinar",
  "velium maul of superiority",
]);
