// Spell lists by class

var BARD_SPELLS = [
  "Chant of Battle",
  "Chant of Chaos",
  "Chant of Flame",
  "Chant of Frost",
  "Chant of Magic",
  "Chant of Plague",
  "Chant of Venom",
  "Chords of Dissonance",
  "Lyssa's Locating Lyric",
  "Selo's Accelerando",
  "Hymn of Restoration",
  "Jonthan's Whistling Warsong",
  "Kelin's Lugubrious Lament",
  "Elemental Rhythms",
  "Magical Monologue",
  "Anthem de Arms",
  "Cinda's Charismatic Carillon",
  "Brusco's Boastful Bellow",
  "Purifying Rhythms",
  "Lyssa's Cataloging Libretto",
  "Kelin's Lucid Lullaby",
  "Song of Sustenance",
  "Tarew's Aquatic Ayre",
  "Guardian Rhythms",
  "Denon's Disruptive Discord",
  "Shauri's Sonorous Clouding",
  "Cassindra's Chant of Clarity",
  "Largo's Melodic Binding",
  "Melanie's Mellifluous Motion",
  "Alenia's Disenchanting Melody",
  "Selo's Consonant Chain",
  "Lyssa's Veracious Concord",
  "Psalm of Warmth",
  "Selo's Rhythm of Speed",
  "Angstlich's Appalling Screech",
  "Solon's Song of the Sirens",
  "Crission's Pixie Strike",
  "Psalm of Vitality",
  "Amplification",
  "Fufil's Curtailing Chant",
  "Chant of Magic",
  "Agilmente's Aria of Eagles",
  "Cassindra's Chorus of Clarity",
  "Psalm of Cooling",
  "Cantata of Soothing",
  "Lyssa's Solidarity of Vision",
  "Denon's Dissension",
  "Vilia's Verses of Celerity",
  "Psalm of Purity",
  "Tuyen's Chant of Flame",
  "Chant of Flame",
  "Katta's Song of Sword Dancing",
  "Blade Dance",
  "Solon's Bewitching Bravura",
  "Sionachie's Dreams",
  "Syvelian's Anti-Magic Aria",
  "Psalm of Mystic Shielding",
  "McVaxius' Berserker Crescendo",
  "Tuyen's Chant of Disease",
  "Chant of Plague",
  "Denon's Desperate Dirge",
  "Cassindra's Elegy",
  "Aria of Asceticism",
  "Jonthan's Provocation",
  "Rizlona's Embers",
  "Tuyen's Chant of Frost",
  "Chant of Frost",
  "Niv's Melody of Preservation",
  "Selo's Chords of Cessation",
  "Selo's Accelerating Chorus",
  "Shield of Songs",
  "Melody of Ervaj",
  "Tuyen's Chant of Poison",
  "Chant of Venom",
  "Verses of Victory",
  "Largo's Assonant Binding",
  "Resistant Discipline",
  "Selo's Song of Travel",
  "Aria of Innocence",
  "Battlecry of the Vah Shir",
  "Nillipus' March of the Wee",
  "Rizlona's Fire",
  "Song of Dawn",
  "Song of Twilight",
  "Elemental Chorus",
  "Fearless Discipline",
  "Selo's Assonant Strain",
  "Vilia's Chorus of Celerity",
  "Aura of Insight",
  "Aura of Insight",
  "Brusco's Bombastic Bellow",
  "Cantata of Replenishment",
  "Deftdance Discipline",
  "Occlusion of Sound",
  "Purifying Chorus",
  "Song of Highsun",
  "Song of Midnight",
  "Cassindra's Insipid Ditty",
  "McVaxius' Rousing Rondo",
  "Soothing Psalm of the Sunrise",
  "Chorus of Replenishment",
  "Dreams of Ayonae",
  "Jonthan's Inspiration",
  "Niv's Harmonic",
  "Denon's Bereavement",
  "Solon's Charismatic Concord",
  "Ancient: Lcea's Lament",
  "Ancient: Lullaby of Shadow",
  "Angstlich's Assonance",
  "Composition of Ervaj",
  "Ervaj's Lost Composition",
  "Fufil's Diminishing Dirge",
  "Kazumi's Note of Preservation",
  "Puretone Discipline",
  "Warsong of the Vah Shir",
  "Saryrn's Scream of Pain",
  "Silent Song of Quellious",
  "Song of the Storm",
  "Song of the Storm Strike",
  "Tuyen's Chant of the Plague",
  "Chant of Plague",
  "Angstlich's Echo of Terror",
  "Dreams of Thule",
  "Druzzil's Disillusionment",
  "Melody of Mischief",
  "Warsong of Zek",
  "Wind of Marr",
  "Psalm of Veeshan",
  "Tuyen's Chant of Ice",
  "Chant of Frost",
  "Tuyen's Chant of Venom",
  "Chant of Venom",
  "Call of the Banshee",
  "Chorus of Marr",
  "Dreams of Terris",
  "Minohten's Purifying Panpipes",
  "Minohten's Purifying Panpipes Rk. II",
  "Minohten's Purifying Panpipes Rk. III",
  "Requiem of Time",
  "Rizlona's Call of Flame",
  "Ancient: Chaos Chant",
  "Chant of Chaos",
  "Call of the Muse",
  "Dark Echo",
  "Echo of the Trusik",
  "Harmony of Sound",
  "Lullaby of Morell",
  "Staccato Rhythms",
  "Staccato Rhythms Rk. II",
  "Staccato Rhythms Rk. III",
  "Tuyen's Chant of Fire",
  "Chant of Flame",
  "War March of the Mastruq"
];

var BEASTLORD_SPELLS = [
  "Salve",
  "Sense Animals",
  "Endure Cold",
  "Cure Disease",
  "Flash of Light",
  "Minor Healing",
  "Inner Fire",
  "Spirit of Sharik",
  "Endure Fire",
  "Sharik's Replenishing",
  "Scale Skin",
  "Fleeting Fury",
  "Blast of Frost",
  "Cure Poison",
  "Spirit of Lightning",
  "Spirit of Lightning Strike",
  "Sicken",
  "Strengthen",
  "Keshuval's Rejuvenation",
  "Spirit of Khaliz",
  "Serpent Sight",
  "Spirit of Bear",
  "Summon Drink",
  "Endure Poison",
  "Light Healing",
  "Spirit of the Blizzard",
  "Spirit of Blizzard Strike",
  "Tainted Breath",
  "Tiny Companion",
  "Drowsy",
  "Spirit of Keshuval",
  "Endure Disease",
  "Shrink",
  "Spirit of Wolf",
  "Enduring Breath",
  "Spirit Strike",
  "Turtle Skin",
  "Herikol's Soothing",
  "Healing",
  "Spirit of Inferno",
  "Spirit of Inferno Strike",
  "Spirit Strength",
  "Spirit Sight",
  "Summon Food",
  "Spirit of Herikol",
  "Summon Companion",
  "Levitate",
  "Ice Spear",
  "Endure Magic",
  "Cancel Magic",
  "Envenomed Breath",
  "Yekan's Recovery",
  "Spirit of Ox",
  "Yekan's Quickening",
  "Greater Healing",
  "Spirit of Monkey",
  "Spirit of the Scorpion",
  "Spirit of Scorpion Strike",
  "Spirit of the Shrew",
  "Spirit of Yekan",
  "Malaria",
  "Raging Strength",
  "Spiritual Light",
  "Spiritual Brawn",
  "Invisibility",
  "Listless Power",
  "Pack Shrew",
  "Counteract Disease",
  "Spirit of Kashek",
  "Spirit of Vermin",
  "Spirit of Vermin Strike",
  "Frenzy",
  "Frost Shard",
  "Protect",
  "Spirit Salve",
  "Vigor of Zehkes",
  "Ward of Calliav",
  "Sha's Lethargy",
  "Resist Disease",
  "Resistant Discipline",
  "Spirit of Wind",
  "Spirit of Wind Strike",
  "Ultravision",
  "Aid of Khurenz",
  "Bond of the Wild",
  "Bond of the Wild Recourse",
  "Health",
  "Spiritual Radiance",
  "Venom of the Snake",
  "Deftness",
  "Spirit of the Storm",
  "Spirit of Storm Strike",
  "Talisman of Tnarg",
  "Fearless Discipline",
  "Furious Strength",
  "Ice Shard",
  "Resist Poison",
  "Spirit of Omakin",
  "Spirit of Snow",
  "Spirit of Snow Strike",
  "Chloroplast",
  "Omakin's Alacrity",
  "Protective Spirit Discipline",
  "Sha's Restoration",
  "Incapacitate",
  "Shifting Shield",
  "Spirit of Flame",
  "Spirit of Flame Strike",
  "Spirit of Zehkes",
  "Dexterity",
  "Stamina",
  "Guard of Calliav",
  "Nullify Magic",
  "Spirit of Khurenz",
  "Talisman of Altuna",
  "Blizzard Blast",
  "Chloroblast",
  "Sha's Ferocity",
  "Spiritual Purity",
  "Alacrity",
  "Bestial Fury Discipline",
  "Savagery",
  "Sha's Advantage",
  "Spirit of Khati Sha",
  "Spiritual Strength",
  "Annul Magic",
  "Counteract Poison",
  "Growl of the Leopard",
  "Growl of the Leopard",
  "Growl of the Leopard",
  "Healing of Sorsha",
  "Infusion of Spirit",
  "Scorpion Venom",
  "Talisman of Shadoo",
  "Spirit of Arag",
  "Spiritual Vigor",
  "Talisman of Kragg",
  "Abolish Disease",
  "Arag's Celerity",
  "Celerity",
  "Frost Spear",
  "Spirit of Rellic",
  "Spirit of Rellic Strike",
  "Talisman of Jasinth",
  "Protection of Calliav",
  "Regrowth",
  "Spirit of Sorsha",
  "Spiritual Dominion",
  "Acumen",
  "Ancient: Frozen Chaos",
  "Ferocity",
  "Plague",
  "Sha's Revenge",
  "Trushar's Frost",
  "Trushar's Mending",
  "Turepta Blood"
];

var BERSERKER_SPELLS = [
  "Corroded Axe",
  "Throw Stone",
  "Blunt Axe",
  "Elbow Strike",
  "Leg Strike",
  "Focused Will Discipline",
  "Steel Axe",
  "Bearded Axe",
  "Head Strike",
  "Mithril Axe",
  "Divertive Strike",
  "Balanced War Axe",
  "Battle Cry",
  "Bonesplicer Axe",
  "Resistant Discipline",
  "Leg Cut",
  "Fleshtear Axe",
  "Cold Steel Cleaving Axe",
  "Fearless Discipline",
  "Head Pummel",
  "Mithril Bloodaxe",
  "Distracting Strike",
  "Rage Axe",
  "War Cry",
  "Inspired Anger Discipline",
  "Cleaving Rage Discipline",
  "Leg Slice",
  "Aura of Rage",
  "Aura of Rage Effect",
  "Bloodseeker's Axe",
  "Reckless Discipline",
  "Battle Cry of Dravel",
  "Focused Fury Discipline",
  "Blind Rage Discipline",
  "Battle Focus Discipline",
  "Battlerage Axe",
  "Burning Rage Discipline",
  "Head Crush",
  "Rage Volley",
  "Sprint Discipline",
  "Healing Will Discipline",
  "Indomitable Discipline",
  "War Cry of Dravel",
  "Ancient: Cry of Chaos",
  "Battle Cry of the Mastruq",
  "Cleaving Anger Discipline",
  "Confusing Strike",
  "Deathfury Axe",
  "Tainted Axe of Hatred"
];

var CLERIC_SPELLS = [
  "Courage",
  "Cure Poison",
  "Divine Aura",
  "Flash of Light",
  "Holy Armor",
  "Lull",
  "Minor Healing",
  "Spook the Dead",
  "Strike",
  "True North",
  "Yaulp",
  "Reckless Strength",
  "Stun",
  "Cure Blindness",
  "Summon Drink",
  "Cure Disease",
  "Light Healing",
  "Ward Undead",
  "Furor",
  "Gate",
  "Soothe",
  "Endure Poison",
  "Fear",
  "Sanctuary",
  "Center",
  "Hammer of Wrath",
  "Root",
  "Endure Fire",
  "Remove Minor Curse",
  "Summon Food",
  "Sense the Dead",
  "Word of Pain",
  "Bind Affinity",
  "Healing",
  "Iony's Lesser Augury",
  "Endure Disease",
  "Invisibility Versus Undead",
  "Symbol of Transal",
  "Halo of Light",
  "Reanimation",
  "Sense Summoned",
  "Cancel Magic",
  "Endure Cold",
  "Expulse Undead",
  "Iony's Lesser Cleansing",
  "Iony's Lesser Exorcism",
  "Smite",
  "Blessing of Piety",
  "Complete Heal",
  "Calm",
  "Spirit Armor",
  "Endure Magic",
  "Holy Might",
  "Yaulp II",
  "Daring",
  "Ward Summoned",
  "Reconstitution",
  "Celestial Remedy",
  "Word of Shadow",
  "Greater Healing",
  "Hammer of Striking",
  "Ward of Vie",
  "Inspire Fear",
  "Symbol of Ryltan",
  "Wave of Fear",
  "Bravery",
  "Counteract Poison",
  "Reparation",
  "Dismiss Undead",
  "Iony's Augury",
  "Remove Lesser Curse",
  "Iony's Cleansing",
  "Iony's Exorcism",
  "Guard",
  "Sermon of the Righteous",
  "Panic the Dead",
  "Word of Spirit",
  "Expulse Summoned",
  "Instill",
  "Revive",
  "Abundant Drink",
  "Counteract Disease",
  "Celestial Health",
  "Divine Barrier",
  "Imbue Amber",
  "Imbue Black Pearl",
  "Imbue Black Sapphire",
  "Imbue Diamond",
  "Imbue Emerald",
  "Imbue Opal",
  "Imbue Peridot",
  "Imbue Plains Pebble",
  "Imbue Rose Quartz",
  "Imbue Ruby",
  "Imbue Sapphire",
  "Imbue Topaz",
  "Mass Imbue Amber",
  "Mass Imbue Black Pearl",
  "Mass Imbue Black Sapphire",
  "Mass Imbue Diamond",
  "Mass Imbue Emerald",
  "Mass Imbue Opal",
  "Mass Imbue Peridot",
  "Mass Imbue Plains Pebble",
  "Mass Imbue Rose Quartz",
  "Mass Imbue Ruby",
  "Mass Imbue Sapphire",
  "Mass Imbue Topaz",
  "Wrath",
  "Resist Poison",
  "Superior Healing",
  "Word of Health",
  "Force",
  "Frenzied Strength",
  "Symbol of Pinzarn",
  "Atone",
  "Renewal",
  "Valor",
  "Abundant Food",
  "Expel Undead",
  "Iony's Greater Augury",
  "Resist Fire",
  "Armor of Protection",
  "Blinding Luminance",
  "Iony's Greater Cleansing",
  "Iony's Greater Exorcism",
  "Tremor",
  "Armor of Faith",
  "Blessing of Faith",
  "Complete Heal",
  "Invoke Fear",
  "Pacify",
  "Resist Disease",
  "Dismiss Summoned",
  "Resuscitate",
  "Turning of the Unnatural",
  "Nullify Magic",
  "Remove Curse",
  "Resist Cold",
  "Complete Heal",
  "Sacred Word",
  "Word of Souls",
  "Guard of Vie",
  "Hammer of Requital",
  "Temperance",
  "Symbol of Naltron",
  "Yaulp III",
  "Resolution",
  "Restoration",
  "Banish Undead",
  "Resist Magic",
  "Celestial Healing",
  "Earthquake",
  "Greater Mass Imbue Amber",
  "Greater Mass Imbue Black Pearl",
  "Greater Mass Imbue Black Sapphire",
  "Greater Mass Imbue Diamond",
  "Greater Mass Imbue Emerald",
  "Greater Mass Imbue Opal",
  "Greater Mass Imbue Peridot",
  "Greater Mass Imbue Plains Pebble",
  "Greater Mass Imbue Rose Quartz",
  "Greater Mass Imbue Ruby",
  "Greater Mass Imbue Sapphire",
  "Greater Mass Imbue Topaz",
  "Retribution",
  "Blessing of Temperance",
  "Healing Light",
  "Shield of Words",
  "Word of Healing",
  "Immobilize",
  "Sound of Force",
  "Expel Summoned",
  "Resurrection",
  "Abolish Poison",
  "Improved Invisibility to Undead",
  "Armor of the Faithful",
  "Word Divine",
  "Ward of the Divine",
  "Ward of the Divine Parry",
  "Death Pact",
  "Dread of Night",
  "Pure Blood",
  "Remedy",
  "Sunskin",
  "Epitaph of Life",
  "Eradicate Poison",
  "Heroic Bond",
  "Heroic Bond",
  "Heroism",
  "Upheaval",
  "Word of Vigor",
  "Annul Magic",
  "Divine Light",
  "Yaulp IV",
  "Eradicate Curse",
  "Mark of Retribution",
  "Protection of Vie",
  "Reckoning",
  "Remove Greater Curse",
  "Symbol of Marzin",
  "Unswerving Hammer of Faith",
  "Aura of the Zealot",
  "Aura of the Zealot Effect",
  "Exile Undead",
  "Fortitude",
  "Stun Command",
  "Wake of Tranquility",
  "Banish Summoned",
  "Cower the Dead",
  "Hammer of Judgment",
  "Judgment",
  "Mark of Karn",
  "Paralyzing Earth",
  "Reviviscence",
  "Yaulp V",
  "Aegis",
  "Bulwark of Faith",
  "Trepidation",
  "Ward of Rebuke",
  "Ward of Rebuke Parry",
  "Word of Restoration",
  "Antidote",
  "Blessed Armor of the Risen",
  "Enforced Reverence",
  "Eradicate Disease",
  "Ethereal Light",
  "Hammer of Divinity",
  "Naltron's Mark",
  "Celestial Elixir",
  "Deistic Voice",
  "Ethereal Remedy",
  "Imbue Valor",
  "The Unspoken Word",
  "Aegolism",
  "Ancient: Gift of Aegolism",
  "Ancient: High Priest's Bulwark",
  "Banishment of Shadows",
  "Blessing of Aegolism",
  "Divine Intervention",
  "Ethereal Elixir",
  "Hammer of Souls",
  "Marzin's Mark",
  "Word of Redemption",
  "Death's Despair",
  "Faith",
  "Larger Reviviscence",
  "Supernal Remedy",
  "Symbol of Kazad",
  "Tarnation",
  "Ward of Gallantry",
  "Ward of Vengeance",
  "Ward of Vengeance Parry",
  "Blessing of Reverence",
  "Complete Heal",
  "Bulwark of Vie",
  "Condemnation",
  "Greater Immobilize",
  "Sermon of Penitence",
  "Supernal Elixir",
  "Virtue",
  "Deistic Bellow",
  "Hammer of Damnation",
  "Kazad's Mark",
  "Resist Corruption",
  "Resist Corruption Rk. II",
  "Resist Corruption Rk. III",
  "Sound of Might",
  "Supernal Light",
  "Aura of Reverence",
  "Complete Heal",
  "Catastrophe",
  "Destroy Undead",
  "Expunge Corruption",
  "Expunge Corruption Rk. II",
  "Expunge Corruption Rk. III",
  "Mark of Kings",
  "Petrifying Earth",
  "Shared Purity",
  "Shared Purity Rk. II",
  "Shared Purity Rk. III",
  "Word of Replenishment",
  "Ancient: Chaos Censure",
  "Armor of the Zealot",
  "Hand of Virtue",
  "Holy Elixir",
  "Holy Light",
  "Mark of the Righteous",
  "Order",
  "Pacification",
  "The Silent Command",
  "Yaulp VI"
];

var DRUID_SPELLS = [
  "Burst of Flame",
  "Dance of the Fireflies",
  "Endure Fire",
  "Flame Lick",
  "Lull Animal",
  "Minor Healing",
  "Panic Animal",
  "Sense Animals",
  "Skin like Wood",
  "Snare",
  "Tangling Weeds",
  "Grasping Roots",
  "Ward Summoned",
  "Burst of Fire",
  "Whirling Wind",
  "Camouflage",
  "Cure Disease",
  "Invoke Lightning",
  "Cure Poison",
  "Gate",
  "Harmony",
  "Enduring Breath",
  "Firefist",
  "Treeform",
  "Shield of Thistles",
  "Strength of Earth",
  "Thistlecoat",
  "Ignite",
  "Invisibility Versus Animals",
  "Remove Minor Curse",
  "Endure Cold",
  "Light Healing",
  "Protection of Wood",
  "Starshine",
  "Spirit of Wolf",
  "Stinging Swarm",
  "Summon Drink",
  "Halo of Light",
  "Reebo's Lesser Augury",
  "Summon Food",
  "Bind Affinity",
  "Cascade of Hail",
  "Befriend Animal",
  "Expulse Summoned",
  "See Invisible",
  "Levitate",
  "Reebo's Lesser Cleansing",
  "Reebo's Lesser Exorcism",
  "Skin like Rock",
  "Calm Animal",
  "Ring of Karana",
  "Ring of Surefall Glade",
  "Terrorize Animal",
  "Careless Lightning",
  "Dizzying Wind",
  "Ring of Butcher",
  "Barbcoat",
  "Ring of Commons",
  "Ring of Toxxulia",
  "Shield of Barbs",
  "Tiny Companion",
  "Cancel Magic",
  "Feral Spirit",
  "Lesser Succor",
  "Ring of Grimling",
  "Superior Camouflage",
  "Endure Disease",
  "Endure Poison",
  "Healing",
  "Protection of Rock",
  "Ring of the Nexus",
  "Circle of Blightfire Moors",
  "Primary Anchor Ring",
  "Resist Fire",
  "Ring of Blightfire Moors",
  "Ring of Ro",
  "Ring of Stonebrunt",
  "Secondary Anchor Ring",
  "Wolf Form",
  "Zephyr: Blightfire Moors",
  "Ensnaring Roots",
  "Reebo's Augury",
  "Ring of Steamfont",
  "Spirit of Cheetah",
  "Tremor",
  "Pogonip",
  "Ring of Feerrott",
  "Ring of Lavastorm",
  "Sunbeam",
  "Charm Animals",
  "Dismiss Summoned",
  "Remove Lesser Curse",
  "Ring of Twilight",
  "Creeping Crud",
  "Reebo's Cleansing",
  "Reebo's Exorcism",
  "Ring of the Combines",
  "Skin like Steel",
  "Circle of Butcher",
  "Circle of Karana",
  "Circle of Toxxulia",
  "Immolate",
  "Ring of Knowledge",
  "Ring of Misty",
  "Circle of Surefall Glade",
  "Circle of the Nexus",
  "Ensnare",
  "Scale of Wolf",
  "Succor: East",
  "Bramblecoat",
  "Circle of Commons",
  "Protection of Steel",
  "Shield of Brambles",
  "Beguile Plants",
  "Circle of Stonebrunt",
  "Combust",
  "Counteract Disease",
  "Counteract Poison",
  "Circle of Grimling",
  "Greater Healing",
  "Harmony of Nature",
  "Imbue Emerald",
  "Imbue Plains Pebble",
  "Mass Imbue Emerald",
  "Mass Imbue Plains Pebble",
  "Ring of Dawnshroud",
  "Circle of Lavastorm",
  "Fury of Air",
  "Greater Wolf Form",
  "Resist Cold",
  "Spirit of the Shrew",
  "Circle of Steamfont",
  "Earthquake",
  "Lightning Strike",
  "Reebo's Greater Augury",
  "Ring of Iceclad",
  "Circle of Feerrott",
  "Circle of Iceclad",
  "Circle of Ro",
  "Drones of Doom",
  "Succor: Butcher",
  "Zephyr: Nexus",
  "Zephyr: Toxxulia",
  "Beguile Animals",
  "Circle of the Combines",
  "Circle of Twilight",
  "Expel Summoned",
  "Ring of Great Divide",
  "Zephyr: Butcherblock",
  "Zephyr: Iceclad",
  "Endure Magic",
  "Healing Water",
  "Reebo's Greater Cleansing",
  "Reebo's Greater Exorcism",
  "Regeneration",
  "Strength of Stone",
  "Zephyr: Karana",
  "Pack Shrew",
  "Pack Spirit",
  "Primary Anchor Circle",
  "Secondary Anchor Circle",
  "Share Wolf Form",
  "Zephyr: Commonlands",
  "Zephyr: Stonebrunt",
  "Zephyr: Surefall Glade",
  "Circle of Misty",
  "Enveloping Roots",
  "Ring of Wakening Lands",
  "Skin like Diamond",
  "Spirit of Ash",
  "Avalanche",
  "Circle of Dawnshroud",
  "Ro's Fiery Sundering",
  "Shield of Spikes",
  "Spikecoat",
  "Wind of the South",
  "Circle of Great Divide",
  "Circle of Knowledge",
  "Firestrike",
  "Remove Curse",
  "Succor: Ro",
  "Zephyr: Grimling",
  "Nature's Renewal",
  "Pack Regeneration",
  "Protection of Diamond",
  "Ring of Cobalt Scar",
  "Wind of the North",
  "Zephyr: Feerrott",
  "Zephyr: Steamfont",
  "Circle of Wakening Lands",
  "Drifting Death",
  "Form of the Great Wolf",
  "Illusion Benefit Dena",
  "Primary Anchor Push",
  "Secondary Anchor Push",
  "Zephyr: Combines",
  "Zephyr: Primary Anchor",
  "Zephyr: Ro",
  "Zephyr: Secondary Anchor",
  "Savage Spirit",
  "Succor: Lavastorm",
  "Summon Companion",
  "Zephyr: Twilight",
  "Chloroplast",
  "Circle of Cobalt Scar",
  "Fixation of Ro",
  "Zephyr: Great Divide",
  "Allure of the Wild",
  "Banish Summoned",
  "Dustdevil",
  "Nullify Magic",
  "Zephyr: Wakening Lands",
  "Greater Mass Imbue Emerald",
  "Greater Mass Imbue Plains Pebble",
  "Resist Disease",
  "Resist Poison",
  "Storm Strength",
  "Superior Healing",
  "Zephyr: Cobalt Scar",
  "Engulfing Roots",
  "Pack Chloroplast",
  "Share Form of the Great Wolf",
  "Illusion Benefit Dena",
  "Zephyr: Misty",
  "Lightning Blast",
  "Skin like Nature",
  "Succor: North",
  "Zephyr: Knowledge",
  "Ice",
  "Shield of Thorns",
  "Thorncoat",
  "Zephyr: Lavastorm",
  "Fire",
  "Improved Superior Camouflage",
  "Starfire",
  "Upheaval",
  "Forest's Renewal",
  "Legacy of Spike",
  "Protection of Nature",
  "Resist Magic",
  "Vengeance of the Wild",
  "Everlasting Breath",
  "Levitation",
  "Tangle",
  "Circle of Winter",
  "Repulse Animal",
  "Ring of Tranquility",
  "Breath of Ro",
  "Call of Karana",
  "Circle of Arcstone",
  "Circle of Summer",
  "Circle of Undershore",
  "Egress I",
  "Feral Pack",
  "Foliage Shield",
  "Pure Blood",
  "Ring of Arcstone",
  "Ring of Barindu",
  "Ring of Natimbi",
  "Ring of Undershore",
  "Zephyr: Undershore",
  "Glamour of Tunare",
  "Ring of Bloodfields",
  "Spirit of Scale",
  "Winged Death",
  "Blizzard",
  "Circle of Natimbi",
  "Circle of Tranquility",
  "Eradicate Curse",
  "Form of the Howler",
  "Regrowth",
  "Remove Greater Curse",
  "Ring of Buried Sea",
  "Scoriae",
  "Spirit of Eagle",
  "Annul Magic",
  "Aura of the Grove",
  "Aura of the Grove Effect",
  "Chloroblast",
  "Circle of Barindu",
  "Circle of Bloodfields",
  "Exile Summoned",
  "Frost",
  "Girdle of Karana",
  "Nature Walker's Behest",
  "Tunare's Request",
  "Vengeance of Nature",
  "Bladecoat",
  "Breath of Karana",
  "Engorging Roots",
  "Ro's Smoldering Disjunction",
  "Wake of Karana",
  "Zephyr: Arcstone",
  "Zephyr: Natimbi",
  "Bonds of Tunare",
  "Imbue Storm",
  "Instinctual Fear",
  "Natureskin",
  "Succor",
  "Zephyr: Barindu",
  "Zephyr: Bloodfields",
  "Zephyr: Dawnshroud",
  "Zephyr: Tranquility",
  "Circle of Seasons",
  "Eradicate Disease",
  "Eradicate Poison",
  "Fist of Karana",
  "Regrowth of the Grove",
  "Shield of Blades",
  "Tunare's Renewal",
  "Circle of Buried Sea",
  "Incarnate Anew",
  "Legacy of Thorn",
  "Protection of the Cabbage",
  "Spirit of Oak",
  "Wildfire",
  "Ancient: Legacy of Blades",
  "Ancient: Starfire of Ro",
  "Banishment",
  "Circle of The Steppes",
  "Entrapping Roots",
  "Form of the Hunter",
  "Mask of the Hunter",
  "Mask of the Stalker",
  "Moonfire",
  "Nature's Recovery",
  "Nature's Touch",
  "Protection of the Glades",
  "Ring of The Steppes",
  "Teleport Guild Hall Anchor",
  "Zephyr: The Steppes",
  "Catastrophe",
  "Cure Corruption",
  "Cure Corruption Rk. II",
  "Cure Corruption Rk. III",
  "Earthen Roots",
  "Entangle",
  "Hand of Ro",
  "Instinctual Panic",
  "Mire Thorns",
  "Replenishment",
  "Storm's Fury",
  "Winter's Storm",
  "Flight of Eagles",
  "Immolation of Ro",
  "Karana's Rage",
  "Nature's Might",
  "Ring of Slaughter",
  "Ro's Illumination",
  "Blessing of Replenishment",
  "Command of Tunare",
  "E`ci's Frosty Breath",
  "Nature's Infusion",
  "Protection of the Nine",
  "Resist Corruption",
  "Resist Corruption Rk. II",
  "Resist Corruption Rk. III",
  "Shield of Bracken",
  "Swarming Death",
  "Brackencoat",
  "Chant of the Napaea",
  "Chant of the Napaea Rk. II",
  "Chant of the Napaea Rk. III",
  "Circle of Slaughter",
  "Karana's Renewal",
  "Protection of Seasons",
  "Savage Roots",
  "Summer's Flame",
  "Vengeance of Tunare",
  "Zephyr: Buried Sea",
  "Ancient: Chaos Frost",
  "Blessing of the Nine",
  "Destroy Summoned",
  "Legacy of Bracken",
  "Mask of the Forest",
  "Sylvan Embers",
  "Sylvan Fire",
  "Sylvan Infusion",
  "Winter's Frost"
];

var ENCHANTER_SPELLS = [
  "Lull",
  "Minor Shielding",
  "Pendril's Animation",
  "Reclaim Energy",
  "Shallow Breath",
  "Strengthen",
  "Taper Enchantment",
  "True North",
  "Weaken",
  "Illusion: Human",
  "Juli's Animation",
  "Mesmerize",
  "Tashina",
  "Color Flux",
  "Fear",
  "Haze",
  "Illusion: Half-Elf",
  "Enfeeblement",
  "Gate",
  "Invisibility",
  "Suffocating Sphere",
  "Eye of Confusion",
  "Illusion: Wood Elf",
  "Sentinel",
  "Lesser Shielding",
  "Root",
  "See Invisible",
  "Soothe",
  "Cancel Magic",
  "Chaotic Feedback",
  "Enchant Silver",
  "Mass Enchant Silver",
  "Mircyl's Animation",
  "Alliance",
  "Bind Sight",
  "Enchant Clay",
  "Illusion: Gnome",
  "Mass Enchant Clay",
  "Ebbing Strength",
  "Kilan's Animation",
  "Languid Pace",
  "Whirl Till You Hurl",
  "Illusion: Burning Nekhon",
  "Illusion Benefit Levitation",
  "Illusion: Dark Elf",
  "Illusion: Kedge",
  "Illusion Benefit Levitation",
  "Illusion: Simple Gnoll",
  "Illusion: Steam Suit",
  "Memory Blur",
  "Mist",
  "Serpent Sight",
  "Charm",
  "Choke",
  "Greater Mass Enchant Silver",
  "Illusion: High Elf",
  "Intellectual Advancement",
  "Mass Thicken Mana",
  "Thicken Mana",
  "Bind Affinity",
  "Enduring Breath",
  "Greater Mass Enchant Clay",
  "Illusion: Erudite",
  "Illusion: Halfling",
  "Enthrall",
  "Illusion: Dwarf",
  "Rune I",
  "Wuggan's Lesser Appraisal",
  "Breeze",
  "Enchant Electrum",
  "Invisibility Versus Undead",
  "Mass Enchant Electrum",
  "Shalee's Animation",
  "Wuggan's Lesser Discombobulation",
  "Wuggan's Lesser Extrication",
  "Identify",
  "Illusion: Barbarian",
  "Illusion: Tree",
  "Levitate",
  "Quickness",
  "Chase the Moon",
  "Disempower",
  "Focus Crude Spellcaster's Empowering Essence",
  "Focus Makeshift Spellcaster's Empowering Essence",
  "Focus Primitive Spellcaster's Empowering Essence",
  "Focus Rudimentary Spellcaster's Empowering Essence",
  "Mesmerization",
  "Sanity Warp",
  "Shielding",
  "Cloud",
  "Endure Magic",
  "Greater Mass Thicken Mana",
  "Illusion: Ogre",
  "Intellectual Superiority",
  "Sisna's Animation",
  "Calm",
  "Illusion: Troll",
  "Sympathetic Aura",
  "Tashani",
  "Berserker Strength",
  "Crystallize Mana",
  "Feckless Might",
  "Greater Mass Enchant Electrum",
  "Tiny Companion",
  "Benevolence",
  "Color Shift",
  "Focus Mass Crude Spellcaster's Empowering Essence",
  "Focus Mass Makeshift Spellcaster's Empowering Essence",
  "Focus Mass Primitive Spellcaster's Empowering Essence",
  "Focus Mass Rudimentary Spellcaster's Empowering Essence",
  "Illusion: Iksar",
  "Mass Crystallize Mana",
  "Shifting Sight",
  "Alacrity",
  "Chaos Flux",
  "Illusion: Earth Elemental",
  "Rune II",
  "Sagar's Animation",
  "Strip Enchantment",
  "Beguile",
  "Major Shielding",
  "Tepid Deeds",
  "Wuggan's Appraisal",
  "Enchant Gold",
  "Illusion: Skeleton",
  "Mass Enchant Gold",
  "Wuggan's Discombobulation",
  "Wuggan's Extrication",
  "Feedback",
  "Focus Elementary Spellcaster's Empowering Essence",
  "Instill",
  "Listless Power",
  "Clarity",
  "Curse of the Simple Mind",
  "Haunting Visage",
  "Suffocate",
  "Clarify Mana",
  "Obscure",
  "Ultravision",
  "Augmentation",
  "Dyn's Dizzying Draught",
  "Greater Mass Enchant Gold",
  "Illusion: Water Elemental",
  "Illusion Benefit Water Breathing",
  "Nullify Magic",
  "Focus Mass Elementary Spellcaster's Empowering Essence",
  "Illusion: Air Elemental",
  "Illusion Benefit Levitation",
  "Mass Clarify Mana",
  "Uleen's Animation",
  "Ward of Alendar",
  "Entrance",
  "Entrancing Lights",
  "Greater Mass Crystallize Mana",
  "Illusion: Drakkin of Draton`ra",
  "Illusion: Drakkin of Osh`vir",
  "Illusion: Drakkin of Venesh",
  "Mana Sieve",
  "Boltran's Animation",
  "Greater Shielding",
  "Radiant Visage",
  "Anarchy",
  "Cast Sight",
  "Enchant Platinum",
  "Mass Enchant Platinum",
  "Illusion: Fire Elemental",
  "Rune III",
  "Wuggan's Greater Appraisal",
  "Gift of Magic",
  "Insipid Weakness",
  "Wuggan's Greater Discombobulation",
  "Wuggan's Greater Extrication",
  "Focus Modest Spellcaster's Empowering Essence",
  "Insight",
  "Invoke Fear",
  "Pacify",
  "Calming Visage",
  "Gravity Flux",
  "Mind Wipe",
  "Aanya's Animation",
  "Cajoling Whispers",
  "Illusion: Dry Bone",
  "Resist Magic",
  "Shade",
  "Distill Mana",
  "Greater Mass Enchant Platinum",
  "Illusion: Spirit Wolf",
  "Rampage",
  "Wandering Mind",
  "Wandering Mind Recourse",
  "Celerity",
  "Focus Mass Modest Spellcaster's Empowering Essence",
  "Immobilize",
  "Mass Distill Mana",
  "Arch Shielding",
  "Boon of the Garou",
  "Lifetap Strike",
  "Incapacitate",
  "Rune IV",
  "Brilliance",
  "Shiftless Deeds",
  "Tashania",
  "Yegoreff's Animation",
  "Boon of the Clear Mind",
  "Illusion: Werewolf",
  "Pillage Enchantment",
  "Weakness",
  "Bounce",
  "Color Skew",
  "Discordant Mind",
  "Enchant Velium",
  "Summon Companion",
  "Greater Mass Clarify Mana",
  "Greater Mass Enchant Velium",
  "Guard of Alendar",
  "Illusion: Scaled Wolf",
  "Leviathan Eyes",
  "Mass Enchant Velium",
  "Focus Simple Spellcaster's Empowering Essence",
  "Illusion: Imp",
  "Illusion Benefit Levitation",
  "Paralyzing Earth",
  "Purify Mana",
  "Reoccurring Amnesia",
  "Adorning Grace",
  "Allure",
  "Blanket of Forgetfulness",
  "Enchant Steel",
  "Berserker Spirit",
  "Dazzle",
  "Gasping Embrace",
  "Mass Purify Mana",
  "Swift Like the Wind",
  "Enchant Adamantite",
  "Enchant Mithril",
  "Group Resist Magic",
  "Kintaz's Animation",
  "Shadow",
  "Enchant Brellium",
  "Focus Mass Simple Spellcaster's Empowering Essence",
  "Mass Enchant Adamantite",
  "Mass Enchant Brellium",
  "Mass Enchant Mithril",
  "Mass Enchant Steel",
  "Collaboration",
  "Focus Spellcaster's Empowering Essence",
  "Improved Invisibility",
  "Theft of Thought",
  "Everlasting Breath",
  "Levitation",
  "Wake of Tranquility",
  "Clarity II",
  "Color Slant",
  "Fascination",
  "Illusion: Guktan",
  "Ordinance",
  "Rune V",
  "Scryer's Trespass",
  "Scryer's Trespass Recourse",
  "Trickster's Augmentation",
  "Trickster's Torment",
  "Aanya's Quickening",
  "Boltran's Agacerie",
  "Cripple",
  "Recant Magic",
  "Beguiling Visage",
  "Dementia",
  "Focus Mass Spellcaster's Empowering Essence",
  "Glamour of Kintaz",
  "Illusion: Orc",
  "Illusion: Vah Shir",
  "Shield of the Magi",
  "Beguiler's Aura",
  "Beguiler's Aura Effect",
  "Focus Refined Spellcaster's Empowering Essence",
  "Gift of Insight",
  "Illusion: Frost Bone",
  "Largarn's Lamentation",
  "Memory Flux",
  "Protection of Alendar",
  "Wind of Tashani",
  "Zumaik's Animation",
  "Augment",
  "Gift of Pure Thought",
  "Horrifying Visage",
  "Imbue Disease",
  "Imbue Justice",
  "Overwhelming Splendor",
  "Torment of Argli",
  "Trepidation",
  "Enlightenment",
  "Forlorn Deeds",
  "Imbue Earth",
  "Imbue Nightmare",
  "Imbue Storm",
  "Imbue Torment",
  "Phobia",
  "Tashanian",
  "Umbra",
  "Bedlam",
  "Dementing Visions",
  "Fetter",
  "Glamorous Visage",
  "Imbue Valor",
  "Imbue War",
  "Reflect",
  "Wondrous Rapidity",
  "Asphyxiate",
  "Focus Mass Refined Spellcaster's Empowering Essence",
  "Greater Mass Distill Mana",
  "Imbue Air",
  "Rapture",
  "Ancient: Chaotic Visions",
  "Ancient: Eternal Rapture",
  "Dictate",
  "Focus Intricate Spellcaster's Empowering Essence",
  "Gift of Brilliance",
  "Imbue Fire",
  "Imbue Water",
  "Koadic's Endless Intellect",
  "Speed of the Brood",
  "Visions of Grandeur",
  "Wind of Tashanian",
  "Apathy",
  "Arcane Rune",
  "Boggle",
  "Greater Fetter",
  "Howl of Tashan",
  "Rune of the Scale",
  "Rune of Zebuxoruk",
  "Shield of the Arcane",
  "Aeldorb's Animation",
  "Beckon",
  "Guard of Druzzil",
  "Jitterskin",
  "Pacification",
  "Speed of Vallon",
  "Strangle",
  "Word of Morell",
  "Bulwark of Alendar",
  "Color Cloud",
  "Night's Dark Terror",
  "Lifetap Strike",
  "Sleep",
  "Torment of Scio",
  "Tranquility",
  "Uproar",
  "Bliss",
  "Command of Druzzil",
  "Focus Mass Intricate Spellcaster's Empowering Essence",
  "Insanity",
  "Shield of Maelin",
  "Ancient: Chaos Madness",
  "Bliss of the Nihil",
  "Dreary Deeds",
  "Focus Elaborate Spellcaster's Empowering Essence",
  "Illusion: Froglok",
  "Illusion: Kunark Goblin",
  "Madness of Ikkibi",
  "Vallon's Quickening",
  "Voice of Quellious"
];

var MAGICIAN_SPELLS = [
  "Burst of Flame",
  "Fire Flux",
  "Flare",
  "Minor Shielding",
  "Reclaim Energy",
  "Summon Dagger",
  "Summon Drink",
  "Summon Food",
  "True North",
  "Elementalkin: Water",
  "Summon Bandages",
  "Summon Brass Choker",
  "Elementalkin: Fire",
  "Sense Summoned",
  "Summon Wisp",
  "Burn",
  "Elementalkin: Air",
  "Gate",
  "Elementalkin: Earth",
  "Flame Bolt",
  "Lesser Shielding",
  "Dimensional Pocket",
  "Elementaling: Water",
  "Eye of Zomm",
  "Elementaling: Fire",
  "Renew Elements",
  "Shield of Fire",
  "Shock of Blades",
  "Elementaling: Air",
  "Invisibility",
  "Staff of Tracing",
  "Summon Linen Mantle",
  "Elementaling: Earth",
  "Summon Fang",
  "Ward Summoned",
  "Cancel Magic",
  "Elemental: Water",
  "Rain of Blades",
  "Summon Tarnished Bauble",
  "Burnout",
  "Elemental: Fire",
  "Summon Elemental Defender",
  "Bind Affinity",
  "Column of Fire",
  "Elemental: Air",
  "Elemental: Earth",
  "Identify",
  "Phantom Leather",
  "Wuggan's Lesser Appraisal",
  "Minor Summoning: Water",
  "Staff of Warding",
  "Wuggan's Lesser Discombobulation",
  "Wuggan's Lesser Extrication",
  "Minor Summoning: Fire",
  "Shock of Flame",
  "Summon Heatstone",
  "Summon Throwing Dagger",
  "Focus Crude Spellcaster's Empowering Essence",
  "Focus Primitive Spellcaster's Empowering Essence",
  "Focus Rudimentary Spellcaster's Empowering Essence",
  "Minor Summoning: Air",
  "See Invisible",
  "Shielding",
  "Summon Tiny Ring",
  "Minor Summoning: Earth",
  "Rain of Fire",
  "Summon Phantom Leather",
  "Summon Waterstone",
  "Bolt of Flame",
  "Expulse Summoned",
  "Lesser Summoning: Water",
  "Renew Summoning",
  "Elemental Shield",
  "Lesser Summoning: Fire",
  "Shield of Flame",
  "Tiny Companion",
  "Focus Makeshift Spellcaster's Empowering Essence",
  "Focus Mass Crude Spellcaster's Empowering Essence",
  "Focus Mass Primitive Spellcaster's Empowering Essence",
  "Focus Mass Rudimentary Spellcaster's Empowering Essence",
  "Lesser Summoning: Air",
  "Spear of Warding",
  "Summon Arrows",
  "Summon Jade Bracelet",
  "Summon Wooden Bracelet",
  "Cornucopia",
  "Lesser Summoning: Earth",
  "Summon Silver Choker",
  "Everfount",
  "Flame Flux",
  "Malaise",
  "Summoning: Water",
  "Shock of Spikes",
  "Summoning: Fire",
  "Wuggan's Appraisal",
  "Focus Mass Makeshift Spellcaster's Empowering Essence",
  "Major Shielding",
  "Staff of Runes",
  "Summoning: Air",
  "Wuggan's Discombobulation",
  "Wuggan's Extrication",
  "Dismiss Summoned",
  "Phantom Chain",
  "Summon Phantom Chain",
  "Summoning: Earth",
  "Greater Summoning: Water",
  "Rain of Spikes",
  "Sword of Runes",
  "Expedience",
  "Greater Summoning: Fire",
  "Summon Leather Mantle",
  "Expel Summoned",
  "Greater Summoning: Air",
  "Inferno Shield",
  "Burnout II",
  "Greater Summoning: Earth",
  "Summon Coldstone",
  "Dimensional Hole",
  "Focus Elementary Spellcaster's Empowering Essence",
  "Monster Summoning I",
  "Summon Shiny Bauble",
  "Blaze",
  "Minor Conjuration: Water",
  "Summon Shard of the Core",
  "Greater Shielding",
  "Minor Conjuration: Fire",
  "Nullify Magic",
  "Cinder Bolt",
  "Minor Conjuration: Air",
  "Staff of Symbols",
  "Wuggan's Greater Appraisal",
  "Focus Mass Elementary Spellcaster's Empowering Essence",
  "Minor Conjuration: Earth",
  "Refresh Summoning",
  "Wuggan's Greater Discombobulation",
  "Wuggan's Greater Extrication",
  "Dagger of Symbols",
  "Rain of Lava",
  "Lesser Conjuration: Water",
  "Summon Companion",
  "Lesser Conjuration: Fire",
  "Summon Ring of Flight",
  "Summon Twisted Ring",
  "Barrier of Combustion",
  "Lesser Conjuration: Air",
  "Summon Phantom Plate",
  "Flame Arc",
  "Lesser Conjuration: Earth",
  "Focus Modest Spellcaster's Empowering Essence",
  "Conjuration: Water",
  "Elemental Armor",
  "Phantom Plate",
  "Shock of Swords",
  "Bounce",
  "Conjuration: Fire",
  "Summon Opal Bracelet",
  "Summon: Orb of Exploration",
  "Arch Shielding",
  "Conjuration: Air",
  "Elemental Maelstrom",
  "Conjuration: Earth",
  "Focus Mass Modest Spellcaster's Empowering Essence",
  "Malaisement",
  "Modulating Rod",
  "Primal Remedy",
  "Summon Stone Bracelet",
  "Shield of Lava",
  "Summon Orb",
  "Greater Conjuration: Earth",
  "Ward of Calliav",
  "Burnout III",
  "Greater Conjuration: Fire",
  "Lava Bolt",
  "Banish Summoned",
  "Greater Conjuration: Air",
  "Summon Elemental Blanket",
  "Greater Conjuration: Water",
  "Rain of Swords",
  "Focus Simple Spellcaster's Empowering Essence",
  "Monster Summoning II",
  "Summon Golden Choker",
  "Gift of Xev",
  "Malosi",
  "Scintillation",
  "Summon Silken Mantle",
  "Vocarate: Earth",
  "Bristlebane's Bundle",
  "Char",
  "Elemental Empathy",
  "Elemental Empathy Recourse",
  "Phantom Armor",
  "Summon Brilliant Bauble",
  "Transon's Elemental Infusion",
  "Vocarate: Fire",
  "Annul Magic",
  "Boon of Immolation",
  "Quiver of Marr",
  "Summon Studded Ring",
  "Vocarate: Air",
  "Bandolier of Luclin",
  "Elemental Cloak",
  "Elemental Draw",
  "Elemental Draw Recourse",
  "Focus Mass Simple Spellcaster's Empowering Essence",
  "Kindle",
  "Phantasmal Armor",
  "Scars of Sigil",
  "Shield of the Magi",
  "Summon Iron Bracelet",
  "Summon Ruby Bracelet",
  "Veil of Elements",
  "Vocarate: Water",
  "Burnout IV",
  "Call of the Hero",
  "Earthen Strength",
  "Earthen Strength Effect",
  "Focus Spellcaster's Empowering Essence",
  "Pouch of Quellious",
  "Rage of Zomm",
  "Sirocco",
  "Wrath of the Elements",
  "Cadeau of Flame",
  "Dyzil's Deafening Decoy",
  "Exile Summoned",
  "Mass Mystical Transvergence",
  "Muzzle of Mardu",
  "Rod of Mystical Transvergence",
  "Eye of Tallon",
  "Greater Vocaration: Earth",
  "Imbue Earth",
  "Shock of Steel",
  "Greater Vocaration: Fire",
  "Guard of Calliav",
  "Malosini",
  "Reflect",
  "Transon's Phantasmal Protection",
  "Velocity",
  "Focus Mass Spellcaster's Empowering Essence",
  "Greater Vocaration: Air",
  "Imbue Air",
  "Manastorm",
  "Manifest Elements",
  "Seeking Flame of Seukor",
  "Valiant Companion",
  "Aegis of Ro",
  "Ancient: Burnout Blaze",
  "Ancient: Shock of Sun",
  "Banishment",
  "Focus Refined Spellcaster's Empowering Essence",
  "Greater Vocaration: Water",
  "Imbue Fire",
  "Imbue Water",
  "Maelstrom of Electricity",
  "Mala",
  "Monster Summoning III",
  "Shock of Fiery Blades",
  "Transon's Elemental Renewal",
  "Wind of the Desert",
  "Belt of Magi`Kot",
  "Blade of Walnan",
  "Elemental Barrier",
  "Firebolt of Tallon",
  "Flameshield of Ro",
  "Shield of the Arcane",
  "Summon Glowing Bauble",
  "Summon Platinum Choker",
  "Summon Runed Mantle",
  "Summon Sapphire Bracelet",
  "Summon Spiked Ring",
  "Summon Steel Bracelet",
  "Summon: Lava Orb",
  "Ward of Xegony",
  "Burning Sand",
  "Burnout V",
  "Fist of Ixiblat",
  "Servant of Marr",
  "Sun Storm",
  "Talisman of Return",
  "Xegony's Phantasmal Guard",
  "Black Steel",
  "Blade of The Kedge",
  "Child of Ro",
  "Elemental Silence",
  "Maelstrom of Ro",
  "Malosinia",
  "Summon Jewelry Bag",
  "Destroy Summoned",
  "Focus Mass Refined Spellcaster's Empowering Essence",
  "Girdle of Magi`Kot",
  "Maelstrom of Thunder",
  "Planar Renewal",
  "Protection of Calliav",
  "Shield of Maelin",
  "Ancient: Chaos Vortex",
  "Call of the Arch Mage",
  "Elemental Siphon",
  "Elemental Siphon Recourse",
  "Focus Intricate Spellcaster's Empowering Essence",
  "Monster Summoning IV",
  "Rathe's Son",
  "Rock of Taelosia",
  "Sun Vortex"
];

var MONK_SPELLS = [
  "Throw Stone",
  "Elbow Strike",
  "Focused Will Discipline",
  "Resistant Discipline",
  "Phantom Zephyr",
  "Fearless Discipline",
  "Phantom Wind",
  "Stonestance Discipline",
  "Thunderkick Discipline",
  "Whirlwind Discipline",
  "Voiddance Discipline",
  "Disciple's Aura",
  "Disciple's Aura Effect",
  "Innerflame Discipline",
  "Hundred Fists Discipline",
  "Phantom Echo",
  "Silentfist Discipline",
  "Ashenhand Discipline",
  "Leopard Claw",
  "Planeswalk Discipline",
  "Healing Will Discipline",
  "Speed Focus Discipline",
  "Phantom Call",
  "Ancient: Phantom Chaos",
  "Earthwalk Discipline",
  "Phantom Shadow"
];

var NECROMANCER_SPELLS = [
  "Cavorting Bones",
  "Coldlight",
  "Disease Cloud",
  "Invisibility Versus Undead",
  "Lifetap",
  "Locate Corpse",
  "Minor Shielding",
  "Reclaim Energy",
  "Sense the Dead",
  "Siphon Strength",
  "Siphon Strength Recourse",
  "Fear",
  "Numb the Dead",
  "True North",
  "Endure Cold",
  "Grim Aura",
  "Lifespike",
  "Clinging Darkness",
  "Gate",
  "Leering Corpse",
  "Poison Bolt",
  "Deadeye",
  "Shadow Step",
  "Dark Empathy",
  "Dark Empathy Recourse",
  "Dark Pact",
  "Ward Undead",
  "Gather Shadows",
  "Mend Bones",
  "Vampiric Embrace",
  "Vampiric Embrace",
  "Bone Walk",
  "Impart Strength",
  "Impart Strength Recourse",
  "Lesser Shielding",
  "Leech",
  "Sight Graft",
  "Wave of Enfeeblement",
  "Heat Blood",
  "Scent of Dusk",
  "Spook the Dead",
  "Endure Disease",
  "Engulfing Darkness",
  "Focus Death",
  "Bind Affinity",
  "Convoke Shadow",
  "Lesser Summon Corpse",
  "Lifedraw",
  "Cure Disease",
  "Heart Flutter",
  "Reebo's Lesser Exorcism",
  "Wuggan's Lesser Appraisal",
  "Reebo's Lesser Augury",
  "Reebo's Lesser Cleansing",
  "Shieldskin",
  "Wuggan's Lesser Discombobulation",
  "Wuggan's Lesser Extrication",
  "Banshee Aura",
  "Cancel Magic",
  "Infectious Cloud",
  "Voice Graft",
  "Feign Death",
  "Focus Crude Spellcaster's Empowering Essence",
  "Focus Primitive Spellcaster's Empowering Essence",
  "Focus Rudimentary Spellcaster's Empowering Essence",
  "Form of Chilled Bone",
  "Hungry Earth",
  "Restless Bones",
  "Shielding",
  "Spirit Armor",
  "Identify",
  "Shackle of Bone",
  "Shadow Compact",
  "Shadow Compact Recourse",
  "Allure of Death",
  "Dominate Undead",
  "Track Corpse",
  "Expulse Undead",
  "Shadow Vortex",
  "Shadow Vortex Recourse",
  "Tiny Companion",
  "Animate Dead",
  "Focus Makeshift Spellcaster's Empowering Essence",
  "Focus Mass Crude Spellcaster's Empowering Essence",
  "Focus Mass Primitive Spellcaster's Empowering Essence",
  "Focus Mass Rudimentary Spellcaster's Empowering Essence",
  "Harmshield",
  "Siphon Life",
  "Word of Shadow",
  "Breath of the Dead",
  "Rapacious Subvention",
  "Scent of Shadow",
  "Shock of Poison",
  "Leatherskin",
  "Screaming Terror",
  "Shadow Sight",
  "Intensify Death",
  "Reebo's Exorcism",
  "Rest the Dead",
  "Wuggan's Appraisal",
  "Focus Mass Makeshift Spellcaster's Empowering Essence",
  "Haunting Corpse",
  "Major Shielding",
  "Reebo's Augury",
  "Reebo's Cleansing",
  "Resist Cold",
  "Wuggan's Discombobulation",
  "Wuggan's Extrication",
  "Panic the Dead",
  "Renew Bones",
  "Spirit Tap",
  "Dooming Darkness",
  "Eternities Torment",
  "Word of Spirit",
  "Boil Blood",
  "Dismiss Undead",
  "Summon Dead",
  "Vampiric Curse",
  "Focus Elementary Spellcaster's Empowering Essence",
  "Invoke Fear",
  "Beguile Undead",
  "Call of Bones",
  "Icebone Skeletal Form",
  "Resist Disease",
  "Steelskin",
  "Surge of Enfeeblement",
  "Torbas' Acid Blast",
  "Greater Shielding",
  "Invoke Shadow",
  "Reebo's Greater Exorcism",
  "Wuggan's Greater Appraisal",
  "Focus Mass Elementary Spellcaster's Empowering Essence",
  "Reebo's Greater Augury",
  "Reebo's Greater Cleansing",
  "Root",
  "Venom of the Snake",
  "Wuggan's Greater Discombobulation",
  "Wuggan's Greater Extrication",
  "Augment Death",
  "Scourge",
  "Summon Corpse",
  "Chilling Embrace",
  "Counteract Disease",
  "Word of Souls",
  "Nullify Magic",
  "Scent of Darkness",
  "Expel Undead",
  "Shackle of Spirit",
  "Dark Soul",
  "Drain Spirit",
  "Malignant Dead",
  "Asystole",
  "Focus Modest Spellcaster's Empowering Essence",
  "Summon Companion",
  "Arch Shielding",
  "Dead Man Floating",
  "Ignite Bones",
  "Incinerate Bones",
  "Corporeal Empathy",
  "Corporeal Empathy Recourse",
  "Covetous Subversion",
  "Diamondskin",
  "Bounce",
  "Cackling Bones",
  "Focus Mass Modest Spellcaster's Empowering Essence",
  "Form of Bleached Bone",
  "Pact of Shadow",
  "Pact of Shadow Recourse",
  "Auspice",
  "Dead Men Floating",
  "Banish Undead",
  "Insidious Retrogression",
  "Paralyzing Earth",
  "Cajole Undead",
  "Cascading Darkness",
  "Ignite Blood",
  "Drain Soul",
  "Invoke Death",
  "Lich",
  "Skeletal Form",
  "Bond of Death",
  "Torbas' Poison Blast",
  "Ward of Calliav",
  "Envenomed Bolt",
  "Focus Simple Spellcaster's Empowering Essence",
  "Improved Invisibility to Undead",
  "Dread of Night",
  "Sacrifice",
  "Splurt",
  "Comatose",
  "Defoliation",
  "Degeneration",
  "Degeneration Recourse",
  "Manaskin",
  "Plague",
  "Scent of Terris",
  "Annul Magic",
  "Convergence",
  "Instill",
  "Minion of Shadows",
  "Deflux",
  "Focus Mass Simple Spellcaster's Empowering Essence",
  "Imprecation",
  "Shadowbond",
  "Shadowbond Recourse",
  "Shield of the Magi",
  "Succussion of Shadows",
  "Succussion of Shadows Recourse",
  "Thrall of Bones",
  "Torbas' Venom Blast",
  "Augmentation of Death",
  "Chill Bones",
  "Conglaciation of Bone",
  "Dark Rune",
  "Dark Rune Effect",
  "Focus Spellcaster's Empowering Essence",
  "Infusion",
  "Levant",
  "Skin of the Shadow",
  "Cessation of Cor",
  "Crippling Claudication",
  "Crippling Claudication Recourse",
  "Demi Lich",
  "Skeletal Form",
  "Eidolon Voice",
  "Form of Mottled Bone",
  "Sedulous Subversion",
  "Servant of Bones",
  "Trepidation",
  "Conjure Corpse",
  "Exile Undead",
  "Imbue Nightmare",
  "Unholy Voice",
  "Vexing Mordinia",
  "Guard of Calliav",
  "Imbue Disease",
  "Imbue Torment",
  "Immobilize",
  "Mind Wrack",
  "Mind Wrack Recourse",
  "Pyrocruor",
  "Quivering Veil of Xarn",
  "Reflect",
  "Devouring Darkness",
  "Emissary of Thule",
  "Focus Mass Spellcaster's Empowering Essence",
  "Touch of Night",
  "Ancient: Lifebane",
  "Ancient: Master of Death",
  "Specter Form",
  "Arch Lich",
  "Specter Form",
  "Banishment of Shadows",
  "Death Peace",
  "Enslave Death",
  "Focus Refined Spellcaster's Empowering Essence",
  "Funeral Pyre of Kelador",
  "Gangrenous Touch of Zum`uul",
  "Trucidation",
  "Zevfeer's Theft of Vitae",
  "Zevfeer's Theft of Vitae Recourse",
  "Dark Plague",
  "Eidolon Bellow",
  "Legacy of Zek",
  "Neurotoxin",
  "Shield of the Arcane",
  "Soul Orb",
  "Soul Orb Recourse",
  "Touch of Mujaki",
  "Petrifying Earth",
  "Rune of Death",
  "Saryrn's Kiss",
  "Unholy Bellow",
  "Death's Silence",
  "Embracing Darkness",
  "Force Shield",
  "Greater Immobilize",
  "Horror",
  "Saryrn's Companion",
  "Focus Mass Refined Spellcaster's Empowering Essence",
  "Protection of Calliav",
  "Seduction of Saryrn",
  "Mottled Skeletal Form",
  "Shield of Maelin",
  "Touch of Death",
  "Ancient: Seduction of Chaos",
  "Mottled Skeletal Form",
  "Blood of Thule",
  "Child of Bertoxxulous",
  "Destroy Undead",
  "Focus Intricate Spellcaster's Empowering Essence",
  "Night Fire",
  "Night Stalker",
  "Night Stalker Recourse",
  "Night's Beckon",
  "Word of Terris"
];

var PALADIN_SPELLS = [
  "Salve",
  "Flash of Light",
  "True North",
  "Sense the Dead",
  "Cure Poison",
  "Minor Healing",
  "Cease",
  "Courage",
  "Spook the Dead",
  "Yaulp",
  "Lull",
  "Cure Disease",
  "Light Healing",
  "Desist",
  "Hammer of Wrath",
  "Ward Undead",
  "Holy Armor",
  "Halo of Light",
  "Invisibility Versus Undead",
  "Reckless Strength",
  "Remove Minor Curse",
  "Root",
  "Center",
  "Endure Poison",
  "Reanimation",
  "Hammer of Striking",
  "Symbol of Transal",
  "Soothe",
  "Instrument of Nife",
  "Condemnation of Nife",
  "Healing",
  "Stun",
  "Endure Magic",
  "Expulse Undead",
  "Reconstitution",
  "Spirit Armor",
  "Reparation",
  "Cancel Magic",
  "Symbol of Ryltan",
  "Counteract Poison",
  "Remove Lesser Curse",
  "Divine Vigor",
  "Greater Healing",
  "Daring",
  "Divine Purpose",
  "Endure Disease",
  "Yaulp II",
  "Guard",
  "Revive",
  "Wave of Life",
  "Holy Might",
  "Calm",
  "Ethereal Cleansing",
  "Valor of Marr",
  "Divine Might",
  "Divine Might Strike",
  "Remove Curse",
  "Dismiss Undead",
  "Symbol of Pinzarn",
  "Thunder of Karana",
  "Valor",
  "Armor of Faith",
  "Divine Aura",
  "Superior Healing",
  "Brell's Steadfast Aegis",
  "Pacify",
  "Renewal",
  "Flame of Light",
  "Resist Disease",
  "Resistant Discipline",
  "Force",
  "Frenzied Strength",
  "Light of Life",
  "Divine Glory",
  "Force of Akera",
  "Expel Undead",
  "Fearless Discipline",
  "Instill",
  "Quellious' Word of Tranquility",
  "Austerity",
  "Divine Favor",
  "Holy Aura",
  "Holy Aura Effect",
  "Holyforge Discipline",
  "Resist Magic",
  "Restoration",
  "Wave of Healing",
  "Breath of Tunare",
  "Counteract Disease",
  "Guard of Piety",
  "Yaulp III",
  "Blessing of Austerity",
  "Healing Wave of Prexus",
  "Nullify Magic",
  "Symbol of Naltron",
  "Celestial Cleansing",
  "Deflection Discipline",
  "Resurrection",
  "Brell's Mountainous Barrier",
  "Divine Strength",
  "Eradicate Curse",
  "Remove Greater Curse",
  "Resolution",
  "Sanctification Discipline",
  "Shield of Words",
  "Yaulp IV",
  "Absolve",
  "Absolve Rk. II",
  "Absolve Rk. III",
  "Greater Immobilize",
  "Guard of Humility",
  "Heroism",
  "Resist Poison",
  "Touch of Nife",
  "Crusader's Touch",
  "Deny Undead",
  "Force of Akilae",
  "Ward of Nife",
  "Ward of Nife Strike",
  "Improved Invisibility to Undead",
  "Light of Nife",
  "Pious Might",
  "Pious Might Strike",
  "Symbol of Marzin",
  "Aura of the Crusader",
  "Eradicate Poison",
  "Heroic Bond",
  "Quellious' Word of Serenity",
  "Supernal Cleansing",
  "Ancient: Force of Chaos",
  "Brell's Stalwart Shield",
  "Bulwark of Faith",
  "Cure Corruption",
  "Cure Corruption Rk. II",
  "Cure Corruption Rk. III",
  "Guidance",
  "Holy Order",
  "Holy Order Strike",
  "Light of Order",
  "Shackles of Tunare",
  "Wave of Marr",
  "Wave of Trushar"
];

var RANGER_SPELLS = [
  "Salve",
  "Glimpse",
  "Flame Lick",
  "Lull Animal",
  "Tangling Weeds",
  "Snare",
  "Skin like Wood",
  "Minor Healing",
  "Endure Fire",
  "Dance of the Fireflies",
  "Hawk Eye",
  "Feet like Cat",
  "Cure Poison",
  "Thistlecoat",
  "Burst of Fire",
  "Camouflage",
  "Grasping Roots",
  "Invoke Lightning",
  "Panic Animal",
  "Ward Summoned",
  "Bind Sight",
  "Firefist",
  "Endure Cold",
  "Ignite",
  "Enduring Breath",
  "Light Healing",
  "Skin like Rock",
  "Cure Disease",
  "Harmony",
  "Shield of Thistles",
  "Stinging Swarm",
  "Strength of Earth",
  "Eyes of the Cat",
  "Spirit of Wolf",
  "Flaming Arrow",
  "Riftwind's Protection",
  "Barbcoat",
  "Cancel Magic",
  "Calm Animal",
  "Healing",
  "See Invisible",
  "Dismiss Summoned",
  "Bramblecoat",
  "Levitate",
  "Call of Sky",
  "Call of Sky Strike",
  "Careless Lightning",
  "Nature's Precision",
  "Skin like Steel",
  "Burning Arrow",
  "Harmony of Nature",
  "Swarm of Pain",
  "Spirit of the Shrew",
  "Spikecoat",
  "Shield of Brambles",
  "Greater Healing",
  "Immolate",
  "Ensnaring Roots",
  "Resist Fire",
  "Superior Camouflage",
  "Force of Nature",
  "Wolf Form",
  "Call of Flame",
  "Pack Shrew",
  "Call of Earth",
  "Jolt",
  "Ensnare",
  "Resistant Discipline",
  "Strength of Nature",
  "Tangle",
  "Falcon Eye",
  "Firestrike",
  "Icewind",
  "Storm Strength",
  "Drones of Doom",
  "Fearless Discipline",
  "Jolting Blades",
  "Jolting Blades Strike",
  "Skin like Diamond",
  "Call of Fire",
  "Call of Fire Strike",
  "Chloroplast",
  "Cinder Jolt",
  "Fire Swarm",
  "Resist Cold",
  "Trueshot Discipline",
  "Chill Sight",
  "Greater Wolf Form",
  "Mark of the Predator",
  "Call of Ice",
  "Call of Ice Strike",
  "Eagle Eye",
  "Nullify Magic",
  "Shield of Spikes",
  "Dustdevil",
  "Skin like Nature",
  "Call of the Predator",
  "Enveloping Roots",
  "Thorncoat",
  "Warder's Protection",
  "Weapon Shield Discipline",
  "Annul Magic",
  "Circle of Winter",
  "Counteract Disease",
  "Counteract Poison",
  "Earthen Embrace",
  "Entangle",
  "Exile Summoned",
  "Call of the Rathe",
  "Chloroblast",
  "Drifting Death",
  "Shield of Thorns",
  "Strength of Tunare",
  "Bladecoat",
  "Circle of Summer",
  "Earthen Roots",
  "Frozen Wind",
  "Brushfire",
  "Feral Form",
  "Nature's Rebuke",
  "Nature's Rebuke Strike",
  "Regrowth",
  "Spirit of the Predator",
  "Ancient: Burning Chaos",
  "Cry of Thunder",
  "Cry of Thunder Strike",
  "Mask of the Stalker",
  "Natureskin",
  "Protection of the Wild",
  "Spirit of Eagle",
  "Sylvan Burn",
  "Sylvan Call",
  "Sylvan Call Strike",
  "Sylvan Light"
];

var ROGUE_SPELLS = [
  "Throw Stone",
  "Elbow Strike",
  "Focused Will Discipline",
  "Sneak Attack",
  "Resistant Discipline",
  "Fearless Discipline",
  "Thief's Vengeance",
  "Counterattack Discipline",
  "Deadeye Discipline",
  "Nimble Discipline",
  "Poison Spurs Trap",
  "Poison Spurs",
  "Kinesthetics Discipline",
  "Blinding Speed Discipline",
  "Duelist Discipline",
  "Rogue's Ploy",
  "Assassin's Strike",
  "Deadly Precision Discipline",
  "Healing Will Discipline",
  "Ancient: Chaos Strike",
  "Kyv Strike",
  "Twisted Chance Discipline"
];

var SHADOW_KNIGHT_SPELLS = [
  "Spike of Disease",
  "Sense the Dead",
  "Locate Corpse",
  "Invisibility Versus Undead",
  "Disease Cloud",
  "Siphon Strength",
  "Siphon Strength Recourse",
  "Leering Corpse",
  "Lifetap",
  "Despair",
  "Numb the Dead",
  "Endure Cold",
  "Clinging Darkness",
  "Fear",
  "Lesser Summon Corpse",
  "Shadow Step",
  "Bone Walk",
  "Lifespike",
  "Scream of Hate",
  "Scream of Hate Recourse",
  "Grim Aura",
  "Deadeye",
  "Ward Undead",
  "Cure Disease",
  "Tiny Companion",
  "Engulfing Darkness",
  "Spook the Dead",
  "Dark Empathy",
  "Dark Empathy Recourse",
  "Convoke Shadow",
  "Vampiric Embrace",
  "Vampiric Embrace",
  "Scream of Pain",
  "Scream of Pain Recourse",
  "Feign Death",
  "Endure Disease",
  "Wave of Enfeeblement",
  "Heat Blood",
  "Lifedraw",
  "Strengthen Death",
  "Gather Shadows",
  "Restless Bones",
  "Shieldskin",
  "Dark Temptation",
  "Terror of Darkness",
  "Spear of Disease",
  "Resist Cold",
  "Shroud of Hate",
  "Shroud of Hate Recourse",
  "Summon Corpse",
  "Cancel Magic",
  "Heart Flutter",
  "Scream of Death",
  "Scream of Death Strike",
  "Shadow Vortex",
  "Shadow Vortex Recourse",
  "Animate Dead",
  "Expulse Undead",
  "Voice of Darkness",
  "Shadow Sight",
  "Blood of Pain",
  "Terror of Shadows",
  "Invoke Fear",
  "Dooming Darkness",
  "Breath of the Dead",
  "Word of Spirit",
  "Summon Dead",
  "Voice of Shadows",
  "Life Leech",
  "Scythe of Darkness",
  "Spear of Pain",
  "Dismiss Undead",
  "Harmshield",
  "Shroud of Pain",
  "Shroud of Pain Recourse",
  "Resistant Discipline",
  "Siphon Life",
  "Abduction of Strength",
  "Abduction of Strength Recourse",
  "Comatose",
  "Malignant Dead",
  "Mental Corruption",
  "Mental Corruption Strike",
  "Rest the Dead",
  "Summon Companion",
  "Boil Blood",
  "Terror of Death",
  "Banshee Aura",
  "Call of Darkness",
  "Fearless Discipline",
  "Panic the Dead",
  "Scythe of Death",
  "Spear of Plague",
  "Torrent of Hate",
  "Torrent of Hate Recourse",
  "Bobbing Corpse",
  "Expel Undead",
  "Shroud of Death",
  "Shroud of Death Strike",
  "Shroud of Undeath",
  "Shroud of Death Strike",
  "Icebone Skeletal Form",
  "Spirit Tap",
  "Unholy Aura Discipline",
  "Voice of Death",
  "Ichor Guard",
  "Soulless Fear",
  "Steelskin",
  "Torrent of Pain",
  "Torrent of Pain Recourse",
  "Conjure Corpse",
  "Drain Spirit",
  "Shadow Voice",
  "Vampiric Curse",
  "Cackling Bones",
  "Deathly Temptation",
  "Icebone Skeletal Form",
  "Nullify Magic",
  "Torrent of Fatigue",
  "Torrent of Fatigue Recourse",
  "Cascading Darkness",
  "Deflection Discipline",
  "Diamondskin",
  "Terror of Terris",
  "Asystole",
  "Augment Death",
  "Cloak of the Akheva",
  "Death Peace",
  "Drain Soul",
  "Leechcurse Discipline",
  "Voice of Terris",
  "Aura of Darkness",
  "Aura of Darkness Recourse",
  "Festering Darkness",
  "Ignite Blood",
  "Improved Invisibility to Undead",
  "Soul Guard",
  "Soulless Panic",
  "Bond of Death",
  "Deny Undead",
  "Shadow Bellow",
  "Touch of Volatis",
  "Zevfeer's Bite",
  "Zevfeer's Bite Recourse",
  "Aura of Pain",
  "Aura of Pain Recourse",
  "Blood of Hate",
  "Shroud of Chaos",
  "Shroud of Chaos Strike",
  "Terror of Thule",
  "Augmentation of Death",
  "Invoke Death",
  "Pact of Hate",
  "Mottled Skeletal Form",
  "Scythe of Innoruuk",
  "Spear of Decay",
  "Ancient: Bite of Chaos",
  "Bite of Chaos Recourse",
  "Aura of Hate",
  "Aura of Hate Recourse",
  "Black Shroud",
  "Black Shroud Strike",
  "Cloak of Luclin",
  "Mental Horror",
  "Mental Horror Strike",
  "Miasmic Spear",
  "Touch of Innoruuk",
  "Voice of Thule"
];

var SHAMAN_SPELLS = [
  "Burst of Flame",
  "Cure Disease",
  "Dexterous Aura",
  "Endure Cold",
  "Flash of Light",
  "Inner Fire",
  "Minor Healing",
  "Strengthen",
  "True North",
  "Cure Poison",
  "Spirit Pouch",
  "Summon Drink",
  "Feet like Cat",
  "Scale Skin",
  "Fleeting Fury",
  "Frost Rift",
  "Sicken",
  "Drowsy",
  "Endure Fire",
  "Gate",
  "Serpent Sight",
  "Spirit of Bear",
  "Summon Food",
  "Cure Blindness",
  "Sense Animals",
  "Spirit Sight",
  "Endure Disease",
  "Tainted Breath",
  "Talisman of the Beast",
  "Light Healing",
  "Remove Minor Curse",
  "Spirit of Wolf",
  "Invisibility Versus Animals",
  "Levitate",
  "Spirit of Snake",
  "Burst of Strength",
  "Endure Poison",
  "Turtle Skin",
  "Disempower",
  "Enduring Breath",
  "Root",
  "Reebo's Lesser Augury",
  "Walking Sleep",
  "Bind Affinity",
  "Reebo's Lesser Cleansing",
  "Reebo's Lesser Exorcism",
  "Spirit Strike",
  "Infectious Cloud",
  "Shrink",
  "Frenzy",
  "Grow",
  "Tiny Companion",
  "Insidious Fever",
  "Vision",
  "Malaise",
  "Spirit of Cat",
  "Spirit Strength",
  "Affliction",
  "Cancel Magic",
  "Endure Magic",
  "Healing",
  "Creeping Vision",
  "Protect",
  "Spirit of Cheetah",
  "Spirit of Monkey",
  "Spirit of Ox",
  "Counteract Disease",
  "Poison Storm",
  "Scale of Wolf",
  "Cannibalize",
  "Frost Strike",
  "Reebo's Augury",
  "Regeneration",
  "Envenomed Breath",
  "Reebo's Cleansing",
  "Reebo's Exorcism",
  "Remove Lesser Curse",
  "Resist Cold",
  "Befriend Animal",
  "Form of the Bear",
  "Rising Dexterity",
  "Counteract Poison",
  "Quickness",
  "Ultravision",
  "Invisibility",
  "Resist Fire",
  "Tagar's Insects",
  "Alluring Aura",
  "Raging Strength",
  "Greater Healing",
  "Imbue Amber",
  "Imbue Diamond",
  "Imbue Ivory",
  "Imbue Jade",
  "Imbue Sapphire",
  "Listless Power",
  "Mass Imbue Amber",
  "Mass Imbue Diamond",
  "Mass Imbue Ivory",
  "Mass Imbue Jade",
  "Mass Imbue Sapphire",
  "Spirit of the Shrew",
  "Fury",
  "Health",
  "Resist Disease",
  "Nimble",
  "Scourge",
  "Shifting Shield",
  "Charm Animals",
  "Companion Spirit",
  "Malaisement",
  "Talisman of Tnarg",
  "Instill",
  "Reebo's Greater Augury",
  "Winter's Roar",
  "Curse",
  "Pack Shrew",
  "Reebo's Greater Cleansing",
  "Reebo's Greater Exorcism",
  "Shock of the Tainted",
  "Resist Poison",
  "Tumultuous Strength",
  "Assiduous Vision",
  "Gale of Poison",
  "Spirit of Bih`Li",
  "Glamour",
  "Venom of the Snake",
  "Vigilant Spirit",
  "Cannibalize II",
  "Insidious Malady",
  "Remove Curse",
  "Togor's Insects",
  "Blinding Luminance",
  "Chloroplast",
  "Deftness",
  "Furious Strength",
  "Spirit Salve",
  "Summon Companion",
  "Talisman of Altuna",
  "Agility",
  "Guardian Spirit",
  "Incapacitate",
  "Alacrity",
  "Blast of Poison",
  "Guardian",
  "Odium",
  "Resist Magic",
  "Stamina",
  "Blizzard Blast",
  "Greater Mass Imbue Amber",
  "Greater Mass Imbue Diamond",
  "Greater Mass Imbue Ivory",
  "Greater Mass Imbue Jade",
  "Greater Mass Imbue Sapphire",
  "Nullify Magic",
  "Stoicism",
  "Frenzied Spirit",
  "Rage",
  "Superior Healing",
  "Harnessing of Spirit",
  "Strength",
  "Charisma",
  "Shock of Venom",
  "Abolish Disease",
  "Dexterity",
  "Malosi",
  "Envenomed Bolt",
  "Infusion of Spirit",
  "Plague",
  "Kragg's Salve",
  "Spirit of the Puma",
  "Puma Maw",
  "Spirit Quickening",
  "Talisman of Jasinth",
  "Everlasting Breath",
  "Immobilize",
  "Levitation",
  "Turgur's Insects",
  "Blood of Nadox",
  "Disinfecting Aura",
  "Eradicate Disease",
  "Insidious Decay",
  "Primal Essence",
  "Regrowth",
  "Spirit of Scale",
  "Cripple",
  "Deliriously Nimble",
  "Talisman of Shadoo",
  "Anathema",
  "Blast of Venom",
  "Cannibalize III",
  "Eradicate Curse",
  "Ice Strike",
  "Plague of Insects",
  "Remove Greater Curse",
  "Riotous Health",
  "Shroud of the Spirits",
  "Annul Magic",
  "Chloroblast",
  "Form of the Great Bear",
  "Idol of Malo",
  "Idol of Malo Effect",
  "Spirit of the Howler",
  "Talisman of Kragg",
  "Torrent of Poison",
  "Acumen",
  "Bane of Nife",
  "Celerity",
  "Eradicate Poison",
  "Paralyzing Earth",
  "Regrowth of Dar Khura",
  "Imbue Justice",
  "Malosini",
  "Maniacal Strength",
  "Spirit of the Jaguar",
  "Jaguar Maw",
  "Talisman of the Brute",
  "Talisman of the Cat",
  "Acumen of Dar Khura",
  "Cannibalize IV",
  "Imbue Disease",
  "Kragg's Mending",
  "Mortal Deftness",
  "Talisman of Epuration",
  "Talisman of the Rhino",
  "Talisman of the Serpent",
  "Tigir's Insects",
  "Imbue War",
  "Incarnate Anew",
  "Pox of Bertoxxulous",
  "Talisman of the Raptor",
  "Unfailing Reverence",
  "Voice of the Berserker",
  "Ancient: Feral Avatar",
  "Ancient: Scourge of Nife",
  "Avatar",
  "Focus of Spirit",
  "Khura's Focusing",
  "Malo",
  "Primal Avatar",
  "Torpor",
  "Agility of the Wrulan",
  "Cloud of Grummus",
  "Replenishment",
  "Spear of Torment",
  "Spirit of the Leopard",
  "Leopard Maw",
  "True Spirit",
  "Ancestral Guard",
  "Cure Corruption",
  "Cure Corruption Rk. II",
  "Cure Corruption Rk. III",
  "Endurance of the Boar",
  "Focus of Soul",
  "Greater Immobilize",
  "Talisman of the Tribunal",
  "Talisman of the Wrulan",
  "Tnarg's Mending",
  "Blessing of Replenishment",
  "Malicious Decay",
  "Malosinia",
  "Strength of the Diaku",
  "Swift Like the Wind",
  "Talisman of the Boar",
  "Tears of Saryrn",
  "Bane",
  "Breath of Ultor",
  "Chant of the Napaea",
  "Chant of the Napaea Rk. II",
  "Chant of the Napaea Rk. III",
  "Petrifying Earth",
  "Talisman of Celerity",
  "Talisman of the Diaku",
  "Tiny Terror",
  "Velium Strike",
  "Ancient: Chaotic Pain",
  "Balance of the Nihil",
  "Blood of Saryrn",
  "Breath of Trushar",
  "Daluda's Mending",
  "Ferine Avatar",
  "Focus of the Seventh",
  "Malos",
  "Quiescence",
  "Wishka's Favor",
  "Wishka's Favor Rk. II",
  "Wishka's Favor Rk. III"
];

var WARRIOR_SPELLS = [
  "Mercenary Taunt",
  "Throw Stone",
  "Elbow Strike",
  "Focused Will Discipline",
  "Provoke",
  "Resistant Discipline",
  "Fearless Discipline",
  "Bellow",
  "Evasive Discipline",
  "Charge Discipline",
  "Mighty Strike Discipline",
  "Defensive Discipline",
  "Myrmidon's Aura",
  "Myrmidon's Aura Effect",
  "Berate",
  "Furious Discipline",
  "Precision Discipline",
  "Fellstrike Discipline",
  "Fortitude Discipline",
  "Mercenary Area Taunt",
  "Aggressive Discipline",
  "Spirit of Rage Discipline",
  "Whirlwind Blade",
  "Healing Will Discipline",
  "Incite",
  "Ancient: Chaos Cry",
  "Bellow of the Mastruq",
  "Stonewall Discipline"
];

var WIZARD_SPELLS = [
  "Blast of Cold",
  "Frost Bolt",
  "Minor Shielding",
  "Numbing Cold",
  "Sphere of Light",
  "True North",
  "Glimpse",
  "O`Keil's Radiation",
  "Fade",
  "Root",
  "Gate",
  "See Invisible",
  "Shock of Fire",
  "Fingers of Fire",
  "Fire Bolt",
  "Icestrike",
  "Lesser Shielding",
  "Sense Summoned",
  "Shadow Step",
  "Column of Frost",
  "Eye of Zomm",
  "Shock of Ice",
  "Halo of Light",
  "Resistant Skin",
  "O`Keil's Embers",
  "Shock of Lightning",
  "Cancel Magic",
  "Gaze",
  "Bind Affinity",
  "Firestorm",
  "Frost Spiral of Al`Kabor",
  "Shieldskin",
  "Xalirilan's Lesser Appraisal",
  "Identify",
  "Project Lightning",
  "Xalirilan's Lesser Discombobulation",
  "Xalirilan's Lesser Extrication",
  "Flame Shock",
  "Pillar of Fire",
  "Shielding",
  "Bind Sight",
  "Focus Crude Spellcaster's Empowering Essence",
  "Focus Primitive Spellcaster's Empowering Essence",
  "Focus Rudimentary Spellcaster's Empowering Essence",
  "Heat Sight",
  "Invisibility",
  "Lightning Bolt",
  "Force Snap",
  "Instill",
  "Nexus Gate",
  "Fire Spiral of Al`Kabor",
  "Garrison's Mighty Mana Shock",
  "Lesser Evacuate",
  "North Gate",
  "Sight",
  "Tishan's Clash",
  "Tox Gate",
  "Blightfire Moors Gate",
  "Blightfire Moors Portal",
  "Elemental Shield",
  "Fay Gate",
  "Focus Makeshift Spellcaster's Empowering Essence",
  "Focus Mass Crude Spellcaster's Empowering Essence",
  "Focus Mass Primitive Spellcaster's Empowering Essence",
  "Focus Mass Rudimentary Spellcaster's Empowering Essence",
  "Grimling Gate",
  "Primary Anchor Gate",
  "Secondary Anchor Gate",
  "Translocate: Blightfire Moors",
  "Common Gate",
  "Leatherskin",
  "Stonebrunt Gate",
  "Levitate",
  "Nek Gate",
  "Ro Gate",
  "Twilight Gate",
  "Cazic Gate",
  "Lightning Storm",
  "Major Shielding",
  "West Gate",
  "Xalirilan's Appraisal",
  "Cast Force",
  "Column of Lightning",
  "Combine Gate",
  "Focus Mass Makeshift Spellcaster's Empowering Essence",
  "Frost Shock",
  "Xalirilan's Discombobulation",
  "Xalirilan's Extrication",
  "Minor Familiar",
  "Summon Minor Familiar",
  "North Portal",
  "O`Keil's Levity",
  "Yonder",
  "Energy Storm",
  "Evacuate: North",
  "Imbue Fire Opal",
  "Inferno Shock",
  "Bonds of Force",
  "Fay Portal",
  "Knowledge Gate",
  "Stonebrunt Portal",
  "Mass Imbue Fire Opal",
  "Shock Spiral of Al`Kabor",
  "Thunder Strike",
  "Tox Portal",
  "Dawnshroud Gate",
  "Grimling Portal",
  "Magnify",
  "Nexus Portal",
  "Focus Elementary Spellcaster's Empowering Essence",
  "Steelskin",
  "Thunderclap",
  "Circle of Force",
  "O`Keil's Flickering Flame",
  "Evacuate: Fay",
  "Harvest",
  "Iceclad Gate",
  "Lava Storm",
  "Nek Portal",
  "Cazic Portal",
  "Greater Shielding",
  "Iceclad Portal",
  "Twilight Portal",
  "Xalirilan's Greater Appraisal",
  "Combine Portal",
  "Focus Mass Elementary Spellcaster's Empowering Essence",
  "Great Divide Gate",
  "Ice Shock",
  "Nullify Magic",
  "Xalirilan's Greater Discombobulation",
  "Xalirilan's Greater Extrication",
  "Common Portal",
  "Elnerick's Entombment of Ice",
  "Force Spiral of Al`Kabor",
  "Primary Anchor Portal",
  "Secondary Anchor Portal",
  "Translocate: North",
  "Translocate: Stonebrunt",
  "Great Divide Portal",
  "Ro Portal",
  "Tishan's Relocation",
  "Translocate: Fay",
  "Translocate: Nexus",
  "Concussion",
  "Lightning Shock",
  "Markar's Relocation",
  "Translocate: Tox",
  "West Portal",
  "Chill Sight",
  "Evacuate: Ro",
  "Knowledge Portal",
  "Shifting Sight",
  "Translocate: Combine",
  "Wakening Lands Gate",
  "Cobalt Scar Gate",
  "Dawnshroud Portal",
  "Immobilize",
  "Invisibility to Undead",
  "Translocate: Grimling",
  "Diamondskin",
  "Focus Modest Spellcaster's Empowering Essence",
  "Primary Anchor Push",
  "Secondary Anchor Push",
  "Translocate: Common",
  "Translocate: Primary Anchor",
  "Translocate: Secondary Anchor",
  "Vision Shift",
  "Force Strike",
  "Frost Storm",
  "Translocate: Nek",
  "Translocate: Twilight",
  "Elemental Armor",
  "Evacuate: Nek",
  "Greater Mass Imbue Fire Opal",
  "Translocate: West",
  "Wakening Lands Portal",
  "Cobalt Scar Portal",
  "Conflagration",
  "Gravity Flux",
  "Translocate: Ro",
  "Arch Shielding",
  "Bounce",
  "Enticement of Flame",
  "Focus Mass Modest Spellcaster's Empowering Essence",
  "Translocate: Cazic",
  "Lesser Familiar",
  "Summon Lesser Familiar",
  "Supernova",
  "Translocate: Iceclad",
  "Translocate: Knowledge",
  "Alter Plane: Hate",
  "Alter Plane: Sky",
  "Translocate: Great Divide",
  "Evacuate: West",
  "Markar's Clash",
  "Rend",
  "Translocate: Wakening Lands",
  "Paralyzing Earth",
  "Translocate: Cobalt Scar",
  "Wrath of Al`Kabor",
  "Ice Comet",
  "Translocate: Dawnshroud",
  "Ward of Calrena",
  "Focus Simple Spellcaster's Empowering Essence",
  "Levitation",
  "Translocate",
  "Arcstone Gate",
  "Arcstone Portal",
  "Atol's Spectral Shackles",
  "Draught of Fire",
  "Pillar of Frost",
  "Tishan's Discord",
  "Tranquility Gate",
  "Undershore Gate",
  "Undershore Portal",
  "Abscond",
  "Barindu Gate",
  "Frozen Harpoon",
  "Lure of Frost",
  "Manaskin",
  "Natimbi Gate",
  "Tears of Druzzil",
  "Translocate: Group",
  "Annul Magic",
  "Bloodfields Gate",
  "Inferno of Al`Kabor",
  "Jyll's Static Pulse",
  "Elemental Cloak",
  "Familiar",
  "Summon Familiar",
  "Focus Mass Simple Spellcaster's Empowering Essence",
  "Magi Ward",
  "Natimbi Portal",
  "Pillar of Lightning",
  "Shield of the Magi",
  "Thunderbolt",
  "Tranquility Portal",
  "Voltaic Draught",
  "Barindu Portal",
  "Bloodfields Portal",
  "Draught of Jiva",
  "Fire Mark",
  "Fire Mark Effect",
  "Focus Spellcaster's Empowering Essence",
  "Improved Invisibility",
  "Lure of Flame",
  "Plainsight",
  "Tears of Solusek",
  "Translocate: Arcstone",
  "Translocate: Undershore",
  "Decession",
  "Jyll's Zephyr of Ice",
  "Markar's Discord",
  "Retribution of Al`Kabor",
  "Draught of Ice",
  "Evacuate",
  "Eye of Tallon",
  "Guard of Calrena",
  "Pillar of Flame",
  "Translocate: Natimbi",
  "Translocate: Tranquility",
  "Fetter",
  "Lure of Lightning",
  "Manasink",
  "Reflect",
  "Spellshield",
  "Tears of Prexus",
  "Translocate: Bloodfields",
  "Flaming Sword of Xuzl",
  "Focus Mass Spellcaster's Empowering Essence",
  "Invert Gravity",
  "Jyll's Wave of Heat",
  "Vengeance of Al`Kabor",
  "Ancient: Destruction of Ice",
  "Ancient: Greater Concussion",
  "Disintegrate",
  "Elnerick's Electrical Rending",
  "Focus Refined Spellcaster's Empowering Essence",
  "Garrison's Superior Sundering",
  "Greater Familiar",
  "Summon Greater Familiar",
  "Hsagra's Wrath",
  "Ice Spear of Solist",
  "Lure of Ice",
  "Porlos' Fury",
  "Sunderock Springs Gate",
  "Sunderock Springs Portal",
  "Sunstrike",
  "Teleport Guild Hall Anchor",
  "Teleport Primary Anchor",
  "Teleport Secondary Anchor",
  "Translocate: Barindu",
  "Translocate: Sunderock Springs",
  "Winds of Gelid",
  "Claw of Frost",
  "Greater Fetter",
  "Lure of Thunder",
  "Resistant Armor",
  "Shield of the Arcane",
  "Tears of Ro",
  "Draught of Ro",
  "Elemental Barrier",
  "Lure of Ro",
  "Slaughter Gate",
  "Teleport",
  "Agnarr's Thunder",
  "Draught of Lightning",
  "Draught of Thunder",
  "Force Shield",
  "Iceflame of E`ci",
  "Mana Ward",
  "Draught of E`ci",
  "Focus Mass Refined Spellcaster's Empowering Essence",
  "Ice Meteor",
  "Katta Castrum Gate",
  "Protection of Calrena",
  "Shield of Maelin",
  "Slaughter Portal",
  "Tears of Arlyxir",
  "Telekin",
  "Ancient: Strike of Chaos",
  "Black Ice",
  "Focus Intricate Spellcaster's Empowering Essence",
  "Greater Decession",
  "Shock of Magic",
  "Strike of Solusek",
  "Tears of Marr",
  "Telaka",
  "White Fire"
];
